**Contexte : Réalisation d'une étude de grande ampleur sur le thème de la sous-nutrition dans le monde**

**Projet   : Mise en place d'une base de données dans le cadre d'une étude menée par une équipe de la FAO Food and Agriculture Organization of the United Nations (FAO), 
l'un des organes qui composent l'ONU et dont l'objectif est d' « aider à construire un monde libéré de la faim ».**

Beaucoup de données sont disponibles sur le site de la FAO : http://www.fao.org/faostat/fr/#data. 

Les données fournies pour l'étude sont constituées de 5 fichiers:

    fr_animaux.csv          : multiples indicateurs de production des produits animaux en 2013
    fr_population.csv       : population mondiale par pays en 2013
    fr_vegetaux.csv         : multiples indicateurs de production des produits végétaux en 2013
    fr_céréales.csv         : quantité de céréales produites au niveau mondial en 2013    
    fr_sousalimentation.csv : nombre de personnes sous alimentées dans le monde de 2013 à 2017.


**Partie I - DataFrames**

In [63]:
# Import des librairies nécessaires

import warnings
warnings.filterwarnings('ignore')


import pandas as pd
import numpy  as np

#dataPath = '/home/romain/Documents/FichiersFAO/'
#resPath  = '/home/romain/Documents/tab_res/'
resPath = 'C:/Users/adanl/Documents/OC_Projets/tab_res/'
#dataPath = '/home/romain/Documents/FichiersFAO/'
dataPath = 'C:/Users/adanl/Documents/OC_Projets/FAO_2013_Fr/'

# Import des fichiers fournis et création des dataframes

animaux           = pd.read_csv(dataPath+'fr_animaux.csv')
population        = pd.read_csv(dataPath+'fr_population.csv')
vegetaux          = pd.read_csv(dataPath+'fr_vegetaux.csv')
cereales          = pd.read_csv(dataPath+'fr_céréales.csv')
sous_alimentation = pd.read_csv(dataPath+'fr_sousalimentation.csv')
vegetaux.head(2)

Code Domaine                                            Domaine  Code zone  \
0         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
1         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

          Zone  Code Élément                  Élément  Code Produit Produit  \
0  Afghanistan          5511               Production          2511     Blé   
1  Afghanistan          5611  Importations - Quantité          2511     Blé   

   Code année  Année               Unité  Valeur Symbole  \
0        2013   2013  Milliers de tonnes  5169.0       S   
1        2013   2013  Milliers de tonnes  1173.0       S   

  Description du Symbole  
0  Données standardisées  
1  Données standardisées

**Exploration des fichiers sources**

In [64]:
# Taille des datasets

animaux.shape            # 37166 lignes, 14 variables
population.shape         # 175 lignes, 14 variables
vegetaux.shape           # 104871 lignes, 14 variables
cereales.shape           # 891 lignes, 14 variables
sous_alimentation.shape  # 1020 lignes, 15 variables

(1020, 15)

In [65]:
# Décompte par type de variable

animaux.dtypes.value_counts()            # table de flaots
vegetaux.dtypes.value_counts()           # table de flaots
sous_alimentation.dtypes.value_counts()  # table de flaots
population.dtypes.value_counts()         # table de valeurs entières
cereales.dtypes.value_counts()           # table de valeurs entières

object    8
int64     6
dtype: int64

In [66]:
# Décompte des valeurs manquantes par variable

animaux.isna().sum()   #/animaux.shape[0]).sort_values(ascending=True)
vegetaux.isna().sum()
population.isna().sum()
cereales.isna().sum()
(sous_alimentation.isna().sum()/sous_alimentation.shape[0])*100  # la table sous_alimentation comporte près de 41% de valeurs manquantes avant correction. La variable 'Note' n'entre pas en ligne de compte.

Code Domaine                0.000000
Domaine                     0.000000
Code zone                   0.000000
Zone                        0.000000
Code Élément                0.000000
Élément                     0.000000
Code Produit                0.000000
Produit                     0.000000
Code année                  0.000000
Année                       0.000000
Unité                       0.000000
Valeur                     40.686275
Symbole                     0.000000
Description du Symbole      0.000000
Note                      100.000000
dtype: float64


**Question 1 : Calculez le nombre total d’humains sur la planète. Critiquez votre résultat. En cas d’anomalie, analysez et effectuez les corrections nécessaires. 
Donnez le résultat de votre calcul pour l'année 2013.**


In [67]:
population.head(2)

Code Domaine                                            Domaine  Code zone  \
0         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
1         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        202   

             Zone  Code Élément            Élément  Code Produit     Produit  \
0     Afghanistan           511  Population totale          2501  Population   
1  Afrique du Sud           511  Population totale          2501  Population   

   Code année  Année           Unité  Valeur Symbole Description du Symbole  
0        2013   2013  1000 personnes   30552     NaN      Donnée officielle  
1        2013   2013  1000 personnes   52776     NaN      Donnée officielle

In [68]:
# Extraction de l'attribut "Valeur" et conversion en nombre d'habitants, étant donné que dans le fichier initial, 
# les données sont en milliers d'habitants

YEAR = 2013
populations_nombre_habitants = population['Valeur'].sum()*1000
print("\nPopulation mondiale en {} : {}\n".format(YEAR, populations_nombre_habitants))


Population mondiale en 2013 : 8413993000



In [69]:
# Selon le site des Nations Unies ONU info, la population mondiale en juin 2013 était de 7,2 milliards d'habitants
# https://news.un.org/fr/story/2013/06/268542-onu-la-population-mondiale-devrait-atteindre-96-milliards-en-2050

# On note que dans le fichier des populations, l'attribut "Description du Symbole" comporte une ligne 
# "Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées"
# Ne seront donc retenues que les "Données officielles" pour le calcul de la population mondiale

In [70]:
# Sélection de la ligne agrégeant d'autres lignes

population.loc[population['Description du Symbole'] == 'Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées']

Code Domaine                                            Domaine  Code zone  \
33         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...        351   

     Zone  Code Élément            Élément  Code Produit     Produit  \
33  Chine           511  Population totale          2501  Population   

    Code année  Année           Unité   Valeur Symbole  \
33        2013   2013  1000 personnes  1416667       A   

                               Description du Symbole  
33  Agrégat, peut inclure des données officielles,...

In [71]:
# Suppression de la ligne problématique de la Chine

population.drop(33, inplace=True)

# Export de la nouvelle table des populations

population.to_csv(resPath+'pop.csv')

In [72]:
# Calcul du nombre total d'humains sur la planète à partir de données officielles

Population_Totale_Officielle = population['Valeur'].sum()*1000 

In [73]:
print("\nLe nombre total d'\humains sur la planète en {} est de {} d'habitants\n".format(YEAR, Population_Totale_Officielle))


Le nombre total d'\humains sur la planète en 2013 est de 6997326000 d'habitants



**R1 : Population_Totale_Officielle = 6 997 326 000 d'habitants**

In [74]:
# Corrections dans les tables suite à la redondance observée

# Suppression des lignes 'Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées' pour la table 'animaux'
  
animaux.drop(animaux.loc[animaux['Description du Symbole'] == 'Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées'].index, inplace=True)

# Suppression des lignes 'Non disponible' pour la table 'sous_alimentation'

sous_alimentation.drop(sous_alimentation.loc[sous_alimentation['Description du Symbole'] == 'Non disponible'].index, inplace=True)

# Suppression des lignes 'Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées' pour la table 'vegetaux'

vegetaux.drop(vegetaux.loc[vegetaux['Description du Symbole'] == 'Agrégat, peut inclure des données officielles, semi-officielles, estimées ou calculées'].index, inplace=True)

In [75]:
# Vérification : recherche des noms de pays contenant 'Chine' dans la table 'vegetaux'

vegetaux[vegetaux["Zone"].str.contains("Chine")]

Code Domaine                                            Domaine  \
19982         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
19983         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
19984         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
19985         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
19997         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
...            ...                                                ...   
23495         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
23496         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
23497         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
23498         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   
23499         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...   

       Code zone                       Zone  Code Élément  \
19982        351                      Chine           645   
19983        351                      Chine           664   
19984        351                      Chine           674   
19985        351                      Chine           684   
19997        351                      Chine           645   
...          ...                        ...           ...   
23495        214  Chine, Taiwan Province de           674   
23496        214  Chine, Taiwan Province de           684   
23497        214  Chine, Taiwan Province de           664   
23498        214  Chine, Taiwan Province de           674   
23499        214  Chine, Taiwan Province de           684   

                                                 Élément  Code Produit  \
19982  Disponibilité alimentaire en quantité (kg/pers...          2511   
19983     Disponibilité alimentaire (Kcal/personne/jour)          2511   
19984  Disponibilité de protéines en quantité (g/pers...          2511   
19985  Disponibilité de matière grasse en quantité (g...          2511   
19997  Disponibilité alimentaire en quantité (kg/pers...          2805   
...                                                  ...           ...   
23495  Disponibilité de protéines en quantité (g/pers...          2680   
23496  Disponibilité de matière grasse en quantité (g...          2680   
23497     Disponibilité alimentaire (Kcal/personne/jour)          2899   
23498  Disponibilité de protéines en quantité (g/pers...          2899   
23499  Disponibilité de matière grasse en quantité (g...          2899   

                     Produit  Code année  Année               Unité  Valeur  \
19982                    Blé        2013   2013                  kg   63.10   
19983                    Blé        2013   2013  Kcal/personne/jour  546.00   
19984                    Blé        2013   2013     g/personne/jour   17.40   
19985                    Blé        2013   2013     g/personne/jour    2.90   
19997       Riz (Eq Blanchi)        2013   2013                  kg   77.45   
...                      ...         ...    ...                 ...     ...   
23495  Aliments pour enfants        2013   2013     g/personne/jour    0.15   
23496  Aliments pour enfants        2013   2013     g/personne/jour    0.03   
23497           Miscellanees        2013   2013  Kcal/personne/jour   10.00   
23498           Miscellanees        2013   2013     g/personne/jour    0.14   
23499           Miscellanees        2013   2013     g/personne/jour    0.07   

      Symbole Description du Symbole  
19982      Fc        Donnée calculée  
19983      Fc        Donnée calculée  
19984      Fc        Donnée calculée  
19985      Fc        Donnée calculée  
19997      Fc        Donnée calculée  
...       ...                    ...  
23495      Fc        Donnée calculée  
23496      Fc        Donnée calculée  
23497      Fc        Donnée calculée  
23498      Fc        Donnée calculée  
23499      Fc        Donnée calculée  

[2928 rows x 14 columns]

** **

**Question 2 : Identifiez les redondances**

In [76]:
# Voici la valeur que nous allons retrouver par les calculs : Nourriture de blé en France = 6971 milliers de tonnes

nourriture_France = vegetaux.loc[(vegetaux['Zone']    == 'France')
                                &(vegetaux['Élément'] == 'Nourriture')
                                &(vegetaux['Produit'] == 'Blé')
                                ]
nour_blé_fr = nourriture_France['Valeur'].sum()
print('\nNourriture de blé en France : {} milliers de tonnes\n'.format(nour_blé_fr))


Nourriture de blé en France : 6971.0 milliers de tonnes



In [77]:
# 1 - Calcul de la première de l'équation : 'disponibilité intérieure de blé en France'

dispo_int_France = vegetaux.loc[(vegetaux['Zone']     == 'France')
                                &(vegetaux['Élément'] == 'Disponibilité intérieure')
                                &(vegetaux['Produit'] == 'Blé')
                                ]
dispo_int_blé_fr = dispo_int_France['Valeur'].sum()

print('\nDisponibilité intérieure de blé en France : {} milliers de tonnes\n'.format(dispo_int_blé_fr))


Disponibilité intérieure de blé en France : 20298.0 milliers de tonnes



In [78]:
# 2 - Calcul de la deuxième partie de l'équation : ( 7822 + 748 + 358 + 1575 + 2824 )

selec = vegetaux.loc[(vegetaux['Zone'] == 'France')
                                &(vegetaux['Produit']  == 'Blé')
                                &(
                                  (vegetaux['Élément'] == 'Aliments pour animaux')
                                 |(vegetaux['Élément'] == 'Semences')
                                 |(vegetaux['Élément'] == 'Pertes')
                                 |(vegetaux['Élément'] == 'Traitement')
                                 |(vegetaux['Élément'] == 'Autres utilisations (non alimentaire)')
                                 )
                                ]
term_2 = selec['Valeur'].sum()
#elt_1
#aliments_animaux_fr = aliments_animaux_France['Valeur'].sum()
print('\nDeuxième terme : {} milliers de tonnes\n'.format(term_2))


Deuxième terme : 13327.0 milliers de tonnes



In [79]:
# Nourriture de blé en France
# (aliments pour animaux + semences + pertes + traitement + autres utilisations ) = term_2

# nourriture   = disponibilité intérieure - (aliments pour animaux + semences + pertes + traitement + autres utilisations )

nourriture = dispo_int_blé_fr - term_2

print('\nNourriture en blé en France : {} milliers de tonnes\n'.format(nourriture))


Nourriture en blé en France : 6971.0 milliers de tonnes



In [80]:
# 2ème méthode

# Nourriture = production + importation + variation de stock - (exportation + aliments pour animaux + semences + pertes + traitement + autres utilisations)

# 6971 = 38614 + 2055 + 1131 - ( 21502 + 7822 + 748 + 358 + 1575 + 2824 )

# Calcul de la première partie de l'équation

partie_1_blé_fr = vegetaux.loc[(vegetaux['Zone'] == 'France')
                                &(vegetaux['Produit'] == 'Blé')
                                 &
                                 (
                                     (vegetaux['Élément'] == 'Production')
                                    |(vegetaux['Élément'] == 'Importations - Quantité')
                                    |(vegetaux['Élément'] == 'Variation de stock')
                                 )
                                ]
p_1_Fr = partie_1_blé_fr['Valeur'].sum()
print('\nPremière partie {} milliers de tonnes\n'.format(p_1_Fr))
                 


Première partie 41800.0 milliers de tonnes



In [81]:
# Calcul de la deuxième partie de l'opération

selec_2 = vegetaux.loc[(vegetaux['Zone'] == 'France')
                                &(vegetaux['Produit'] == 'Blé')
                                &(
                                  (vegetaux['Élément'] == 'Exportations - Quantité')                                    
                                 |(vegetaux['Élément'] == 'Aliments pour animaux')
                                 |(vegetaux['Élément'] == 'Semences')
                                 |(vegetaux['Élément'] == 'Pertes')
                                 |(vegetaux['Élément'] == 'Traitement')
                                 |(vegetaux['Élément'] == 'Autres utilisations (non alimentaire)')
                                 )
                                ]
p_2_Fr = selec_2['Valeur'].sum()
print('\nDeuxième partie {} milliers de tonnes\n'.format(p_2_Fr))



Deuxième partie 34829.0 milliers de tonnes



In [82]:
# Nourriture = production + importation + variation de stock - (exportation + aliments pour animaux + semences + pertes + traitement + autres utilisations)#38614 + 2055 + 1131 - ( 21502 + 7822 + 748 + 358 + 1575 + 2824 )

Nourriture = p_1_Fr - p_2_Fr # 41800 - 34829

print('\nNourriture en blé en France : {} milliers de tonnes\n'.format(Nourriture))


Nourriture en blé en France : 6971.0 milliers de tonnes




** **

**Question 3 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal puis en kg de protéines.**

In [83]:
# Nous allons préparer une table où seront agrégées toutes les données de production (tables 'animaux' et 'vegetaux') permettant de faire les calculs demandés

# Ajout de la variable "origin" aux tables de production

vegetaux["origin"] = "vegetal"
animaux["origin"]  = "animal"

# Les tables étant constituées des mêmes attributs, on peut les regrouper en un unique dataframe 'df_animx_vegx' par concaténation

df_animx_vegx = [animaux, vegetaux]
df_animx_vegx =  pd.concat(df_animx_vegx, ignore_index = True)

In [84]:
df_animx_vegx.head(2)

Code Domaine                                            Domaine  Code zone  \
0         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
1         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

          Zone  Code Élément                  Élément  Code Produit  \
0  Afghanistan          5511               Production          2731   
1  Afghanistan          5611  Importations - Quantité          2731   

            Produit  Code année  Année               Unité  Valeur Symbole  \
0  Viande de Bovins        2013   2013  Milliers de tonnes   134.0       S   
1  Viande de Bovins        2013   2013  Milliers de tonnes     6.0       S   

  Description du Symbole  origin  
0  Données standardisées  animal  
1  Données standardisées  animal

In [85]:
# Liste des clés de la table 
list(df_animx_vegx)

['Code Domaine',
 'Domaine',
 'Code zone',
 'Zone',
 'Code Élément',
 'Élément',
 'Code Produit',
 'Produit',
 'Code année',
 'Année',
 'Unité',
 'Valeur',
 'Symbole',
 'Description du Symbole',
 'origin']

In [86]:
# Nouvvele présentation de 'df_animx_vegx' afin de rendre les manipulations possibles
                                           
df_animx_vegx = df_animx_vegx.pivot(index=["Zone", "Code zone", "Année", "Produit", "Code Produit", "origin"], \
                              columns="Élément", values="Valeur").reset_index()
                                           

df_animx_vegx = df_animx_vegx.rename_axis(None).rename_axis(None, axis=1)

df_animx_vegx.head()

Zone  Code zone  Année                Produit  Code Produit  \
0  Afghanistan          2   2013       Abats Comestible          2736   
1  Afghanistan          2   2013        Agrumes, Autres          2614   
2  Afghanistan          2   2013  Aliments pour enfants          2680   
3  Afghanistan          2   2013                 Ananas          2618   
4  Afghanistan          2   2013                Bananes          2615   

    origin  Aliments pour animaux  Autres utilisations (non alimentaire)  \
0   animal                    NaN                                    NaN   
1  vegetal                    NaN                                    NaN   
2  vegetal                    NaN                                    NaN   
3  vegetal                    NaN                                    NaN   
4  vegetal                    NaN                                    NaN   

   Disponibilité alimentaire (Kcal/personne/jour)  \
0                                             5.0   
1                                             1.0   
2                                             1.0   
3                                             0.0   
4                                             4.0   

   Disponibilité alimentaire en quantité (kg/personne/an)  ...  \
0                                               1.72       ...   
1                                               1.29       ...   
2                                               0.06       ...   
3                                               0.00       ...   
4                                               2.70       ...   

   Disponibilité de protéines en quantité (g/personne/jour)  \
0                                               0.77          
1                                               0.02          
2                                               0.03          
3                                                NaN          
4                                               0.05          

   Disponibilité intérieure  Exportations - Quantité  Importations - Quantité  \
0                      53.0                      NaN                      NaN   
1                      41.0                      2.0                     40.0   
2                       2.0                      NaN                      2.0   
3                       0.0                      NaN                      0.0   
4                      82.0                      NaN                     82.0   

   Nourriture  Pertes  Production  Semences  Traitement  Variation de stock  
0        53.0     NaN        53.0       NaN         NaN                 NaN  
1        39.0     2.0         3.0       NaN         NaN                 NaN  
2         2.0     NaN         NaN       NaN         NaN                 NaN  
3         0.0     NaN         NaN       NaN         NaN                 NaN  
4        82.0     NaN         NaN       NaN         NaN                 NaN  

[5 rows x 21 columns]

In [87]:
# Simplification des noms de colonnes

df_animx_vegx = df_animx_vegx.rename(columns={"Zone": "pays", "Code zone": "codePays", "Année": "annee", "Produit": "produit", \
                                        "Code Produit": "codeProduit", "Aliments pour animaux": "alim_ani", \
                                        "Autres utilisations (non alimentaire)": "autres_utilisations", \
                                        "Disponibilité alimentaire (Kcal/personne/jour)": "dispo_alim_kcal_p_j", \
                                        "Disponibilité alimentaire en quantité (kg/personne/an)": "dispo_alim_kg_p", \
                                        "Disponibilité de protéines en quantité (g/personne/jour)": "dispo_prot_g_p_j", \
                                        "Disponibilité de matière grasse en quantité (g/personne/jour)": \
                                        "dispo_mat_gr_g_p_j", \
                                        "Disponibilité intérieure": "dispo_int", "Exportations - Quantité": "export", \
                                        "Importations - Quantité": "import", "Nourriture": "nourriture", \
                                        "Pertes": "pertes", "Production": "production", "Semences": "semences", \
                                        "Traitement": "transfo", "Variation de stock": "var_stock"})
df_animx_vegx.head()

pays  codePays  annee                produit  codeProduit   origin  \
0  Afghanistan         2   2013       Abats Comestible         2736   animal   
1  Afghanistan         2   2013        Agrumes, Autres         2614  vegetal   
2  Afghanistan         2   2013  Aliments pour enfants         2680  vegetal   
3  Afghanistan         2   2013                 Ananas         2618  vegetal   
4  Afghanistan         2   2013                Bananes         2615  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   
2       NaN                  NaN                  1.0             0.06  ...   
3       NaN                  NaN                  0.0             0.00  ...   
4       NaN                  NaN                  4.0             2.70  ...   

   dispo_prot_g_p_j  dispo_int  export  import  nourriture  pertes  \
0              0.77       53.0     NaN     NaN        53.0     NaN   
1              0.02       41.0     2.0    40.0        39.0     2.0   
2              0.03        2.0     NaN     2.0         2.0     NaN   
3               NaN        0.0     NaN     0.0         0.0     NaN   
4              0.05       82.0     NaN    82.0        82.0     NaN   

   production  semences  transfo  var_stock  
0        53.0       NaN      NaN        NaN  
1         3.0       NaN      NaN        NaN  
2         NaN       NaN      NaN        NaN  
3         NaN       NaN      NaN        NaN  
4         NaN       NaN      NaN        NaN  

[5 rows x 21 columns]

In [88]:
# Simplification des noms de clés pour la table des populations

population.columns = [
                      'codeDomaine', 'Domaine','codePays','pays', 'codeElement',
                      'Element', 'codeProduit', 'produit','codeAnnee','annee', 'unite', 
                      'valeur', 'symbole','descSymbole'
                     ]
population.head(2)

codeDomaine                                            Domaine  codePays  \
0        FBSH  Bilans Alimentaire (Ancienne méthodologie et p...         2   
1        FBSH  Bilans Alimentaire (Ancienne méthodologie et p...       202   

             pays  codeElement            Element  codeProduit     produit  \
0     Afghanistan          511  Population totale         2501  Population   
1  Afrique du Sud          511  Population totale         2501  Population   

   codeAnnee  annee           unite  valeur symbole        descSymbole  
0       2013   2013  1000 personnes   30552     NaN  Donnée officielle  
1       2013   2013  1000 personnes   52776     NaN  Donnée officielle

In [89]:
# La suite des opérations nécessitant l'utilisation des données de population, nous allons extraire certains attributs de la table des populations
 
pop = population[["codePays", "pays", "annee", "valeur"]]

# Calcul population réelle à partir des données en milliers d'habitants et ajout de la colonne 'nb_habitants'

pop["nb_habitants"] = pop["valeur"] * 1000

# Suppression de la colonne initiale en milliers de personnes

pop.drop(["valeur"], axis=1, inplace=True)
pop.head()

codePays            pays  annee  nb_habitants
0         2     Afghanistan   2013      30552000
1       202  Afrique du Sud   2013      52776000
2         3         Albanie   2013       3173000
3         4         Algérie   2013      39208000
4        79       Allemagne   2013      82727000

In [90]:
# Ajout de la population à 'df_animx_vegx' par jointure de la table agrégée de produits 'df_animx_vegx'  avec la table des populations 'pop'

data_merged = pd.merge(df_animx_vegx, pop, on=['codePays','pays', 'annee'])

# Visualisation des 2 premières lignes de la table issue de la jointure

data_merged.head(2)

pays  codePays  annee           produit  codeProduit   origin  \
0  Afghanistan         2   2013  Abats Comestible         2736   animal   
1  Afghanistan         2   2013   Agrumes, Autres         2614  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   

   dispo_int  export  import  nourriture  pertes  production  semences  \
0       53.0     NaN     NaN        53.0     NaN        53.0       NaN   
1       41.0     2.0    40.0        39.0     2.0         3.0       NaN   

   transfo  var_stock  nb_habitants  
0      NaN        NaN      30552000  
1      NaN        NaN      30552000  

[2 rows x 22 columns]

** **

In [91]:
# Liste des colonnes de la table globale 'data_merged'

list(data_merged)

['pays',
 'codePays',
 'annee',
 'produit',
 'codeProduit',
 'origin',
 'alim_ani',
 'autres_utilisations',
 'dispo_alim_kcal_p_j',
 'dispo_alim_kg_p',
 'dispo_mat_gr_g_p_j',
 'dispo_prot_g_p_j',
 'dispo_int',
 'export',
 'import',
 'nourriture',
 'pertes',
 'production',
 'semences',
 'transfo',
 'var_stock',
 'nb_habitants']

In [92]:
# Extraction des varaibles nécessaires aux calculs

extract_data_merged = data_merged[['codePays',
                   'pays',
                   'codeProduit',
                   'produit',
                   'annee',
                   'origin',
                   'alim_ani',
                   'autres_utilisations',
                   'dispo_alim_kcal_p_j',
                   'dispo_prot_g_p_j',
                   'dispo_alim_kg_p',
                   'dispo_int',
                   'export',
                   'import',
                   'nourriture',
                   'pertes',
                   'semences',
                   'production',
                   'nb_habitants']]
extract_data_merged.head(2)

codePays         pays  codeProduit           produit  annee   origin  \
0         2  Afghanistan         2736  Abats Comestible   2013   animal   
1         2  Afghanistan         2614   Agrumes, Autres   2013  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_prot_g_p_j  \
0       NaN                  NaN                  5.0              0.77   
1       NaN                  NaN                  1.0              0.02   

   dispo_alim_kg_p  dispo_int  export  import  nourriture  pertes  semences  \
0             1.72       53.0     NaN     NaN        53.0     NaN       NaN   
1             1.29       41.0     2.0    40.0        39.0     2.0       NaN   

   production  nb_habitants  
0        53.0      30552000  
1         3.0      30552000

In [93]:
# Préparation de la table de base qui va servir pour beaucoup de calculs

# Calcul disponibilité kcal totale sur 1 an(365 jrs) et ajout de la colonne calculée à la table initiale

extract_data_merged['kcal_item_pays'] = extract_data_merged['dispo_alim_kcal_p_j'] * 365 * extract_data_merged['nb_habitants']

# Calcul de la disponibilité alimentaire totale (en kg) et ajout de la colonne à la table initiale

extract_data_merged["dispo_alim_kg"] = extract_data_merged["dispo_alim_kg_p"] * extract_data_merged['nb_habitants']

# Conversion  de la disponibilité alimentaire en tonnes et ajout de la colonne issue de la conversion à la table initiale

extract_data_merged["dispo_alim_tonnes"] = extract_data_merged["dispo_alim_kg"] / 1000

# Calcul de la disponibilité en protéines pour toute la population et pour 1 an (en  kg). Ajout de la colonne issue de la conversion à la table initiale

extract_data_merged["dispo_prot_kg"] = extract_data_merged["dispo_prot_g_p_j"] / 1000 * extract_data_merged["nb_habitants"] * 365

# Calcul de la disponibilité en kcal pour 1 an(365 jrs), pour toute la population et ajout de la colonne issue de la conversion à la table initiale

extract_data_merged["dispo_alim_kcal"] = extract_data_merged["dispo_alim_kcal_p_j"] * extract_data_merged["nb_habitants"] * 365

# Conversion nourriture de milliers de tonnes en kg

extract_data_merged["nourriture_kg"] = extract_data_merged["nourriture"] * 1000000

# Visualisation

extract_data_merged.head(2)

codePays         pays  codeProduit           produit  annee   origin  \
0         2  Afghanistan         2736  Abats Comestible   2013   animal   
1         2  Afghanistan         2614   Agrumes, Autres   2013  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_prot_g_p_j  ...  \
0       NaN                  NaN                  5.0              0.77  ...   
1       NaN                  NaN                  1.0              0.02  ...   

   pertes  semences  production  nb_habitants  kcal_item_pays  dispo_alim_kg  \
0     NaN       NaN        53.0      30552000    5.575740e+10     52549440.0   
1     2.0       NaN         3.0      30552000    1.115148e+10     39412080.0   

   dispo_alim_tonnes  dispo_prot_kg  dispo_alim_kcal  nourriture_kg  
0           52549.44      8586639.6     5.575740e+10     53000000.0  
1           39412.08       223029.6     1.115148e+10     39000000.0  

[2 rows x 25 columns]

**Question 3.1 : Calculez (pour chaque pays et chaque produit) la disponibilité alimentaire en kcal**

In [94]:
# Extraction des attributs nécessaires

kcal_pays_produit = extract_data_merged[['codePays','pays','codeProduit','produit','kcal_item_pays']]
kcal_pays_produit.head()

codePays         pays  codeProduit                produit  kcal_item_pays
0         2  Afghanistan         2736       Abats Comestible    5.575740e+10
1         2  Afghanistan         2614        Agrumes, Autres    1.115148e+10
2         2  Afghanistan         2680  Aliments pour enfants    1.115148e+10
3         2  Afghanistan         2618                 Ananas    0.000000e+00
4         2  Afghanistan         2615                Bananes    4.460592e+10

In [95]:
# Remplacement des '0' par Nan et suppression des lignes Nan. 
# En effet, au numérateur comme au dénominateur, '0' produit des valeurs de ratio aberrantes de type 0 et infini. 
# Il faut donc les supprimer de la table

kcal_pays_produit['kcal_item_pays'] = kcal_pays_produit['kcal_item_pays'].replace(0.0,np.nan)
dispo_alim_kcal = kcal_pays_produit.dropna()

**R 3.1 - Disponibilité alimentaire en kcal (pour chaque pays et chaque produit)**

In [96]:
print('\nDisponibilité alimentaire en kcal (pour chaque pays et chaque produit):\n')
dispo_alim_kcal.head()


Disponibilité alimentaire en kcal (pour chaque pays et chaque produit):



codePays         pays  codeProduit                produit  kcal_item_pays
0         2  Afghanistan         2736       Abats Comestible    5.575740e+10
1         2  Afghanistan         2614        Agrumes, Autres    1.115148e+10
2         2  Afghanistan         2680  Aliments pour enfants    1.115148e+10
4         2  Afghanistan         2615                Bananes    4.460592e+10
5         2  Afghanistan         2740           Beurre, Ghee    2.564840e+11

**Q3.2 - Disponibilité alimentaire en protéines donnée pour chaque produit et pour chaque pays en g/personne/jour.**

In [97]:
# Extraction de certains attributs de la table de base

dispo_alim_prot = extract_data_merged[['codePays', 'pays','codeProduit','produit','dispo_prot_kg']]

dispo_alim_prot.head()

codePays         pays  codeProduit                produit  dispo_prot_kg
0         2  Afghanistan         2736       Abats Comestible      8586639.6
1         2  Afghanistan         2614        Agrumes, Autres       223029.6
2         2  Afghanistan         2680  Aliments pour enfants       334544.4
3         2  Afghanistan         2618                 Ananas            NaN
4         2  Afghanistan         2615                Bananes       557574.0

In [98]:
#Tri décroissant de la table sur le critère 'disp_proteines_quantite_g_personne_jour'

dispo_alim_prot = dispo_alim_prot.sort_values(by=['dispo_prot_kg'], ascending=False)

# Remplacement des '0' par Nan
dispo_alim_prot['dispo_prot_kg'] = dispo_alim_prot['dispo_prot_kg'].replace(0.0,np.nan)

dispo_alim_prot = dispo_alim_prot.dropna()

**R3.2 - Disponibilité alimentaire en protéines donnée pour chaque produit et pour chaque pays en g/personne/jour.**

In [99]:
print('\nDisponibilité en proteines en grammes par pays et par produit, par personne et par jour:\n')
dispo_alim_prot


Disponibilité en proteines en grammes par pays et par produit, par personne et par jour:



codePays                  pays  codeProduit             produit  \
3284         41   Chine, continentale         2511                 Blé   
3351         41   Chine, continentale         2805    Riz (Eq Blanchi)   
6199        100                  Inde         2511                 Blé   
6266        100                  Inde         2805    Riz (Eq Blanchi)   
3364         41   Chine, continentale         2733    Viande de Suides   
...         ...                   ...          ...                 ...   
5318         86               Grenade         2765           Crustacés   
7539         83              Kiribati         2761  Poissons Eau Douce   
4214         55             Dominique         2766        Cephalopodes   
12229       188  Saint-Kitts-et-Nevis         2766        Cephalopodes   
7029        110                 Japon         2516              Avoine   

       dispo_prot_kg  
3284    8.865481e+09  
3351    7.393801e+09  
6199    6.896599e+09  
6266    5.923123e+09  
3364    5.856376e+09  
...              ...  
5318    3.869000e+02  
7539    3.723000e+02  
4214    2.628000e+02  
12229   1.971000e+02  
7029   -1.717080e+07  

[8916 rows x 5 columns]

**Question 4 : A partir de ces dernières informations, et à partir du poids de la disponibilité alimentaire (pour chaque pays et chaque produit), calculez pour chaque produit le ratio "énergie/poids", que vous donnerez en kcal/kg. Vous pouvez vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la valeur calorique d'un oeuf.**

**Table des ratios d'énergie**

In [100]:
# Sélection des colonnes pour la table des énergies

dm1_kcal = extract_data_merged[['codePays','pays','codeProduit','produit','origin','dispo_alim_kcal','nourriture_kg']]

# Calcul du ratio énergie / masse

dm1_kcal["ratio_kcal_kg"] = dm1_kcal["dispo_alim_kcal"] / dm1_kcal["nourriture_kg"]

# Remplacement des valeurs "infinies" par des NaN

dm1_kcal = dm1_kcal.replace([np.inf, -np.inf], np.nan)

# Suppression des 'nan'

dm1_kcal_dropna = dm1_kcal.dropna()

# Sélection des lignes de ratio non nul

dm1_kcal_p = dm1_kcal_dropna[dm1_kcal_dropna['ratio_kcal_kg']  != 0]

# Tri de la varaible 'ratio' par ordre décroissant

sorted_dm1_kcal_final = dm1_kcal_p.sort_values(by = ['ratio_kcal_kg'], ascending = False)

print('\nTable du ratio "dispo_alim_kcal/nourriture_kg:"\n')
sorted_dm1_kcal_final


Table du ratio "dispo_alim_kcal/nourriture_kg:"



codePays                  pays  codeProduit                  produit  \
2931         40                 Chili         2586  Huil Plantes Oleif Autr   
11756       117   République de Corée         2582   Huile de Germe de Maïs   
11752       117   République de Corée         2572         Huile d'Arachide   
10925       171           Philippines         2580            Huile d'Olive   
3505         44              Colombie         2579          Huile de Sésame   
...         ...                   ...          ...                      ...   
14446       234               Uruguay         2612          Citrons & Limes   
12268       188  Saint-Kitts-et-Nevis         2611      Oranges, Mandarines   
7531         83              Kiribati         2611      Oranges, Mandarines   
12486       244                 Samoa         2612          Citrons & Limes   
12513       244                 Samoa         2767       Mollusques, Autres   

        origin  dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
2931   vegetal     1.929390e+10      1000000.0   19293.900000  
11756  vegetal     1.798100e+10      1000000.0   17980.995000  
11752  vegetal     1.798100e+10      1000000.0   17980.995000  
10925  vegetal     3.591381e+10      2000000.0   17956.905000  
3505   vegetal     1.763716e+10      1000000.0   17637.165000  
...        ...              ...            ...            ...  
14446  vegetal     1.243555e+09     15000000.0      82.903667  
12268  vegetal     7.884000e+07      1000000.0      78.840000  
7531   vegetal     7.446000e+07      1000000.0      74.460000  
12486  vegetal     6.935000e+07      1000000.0      69.350000  
12513   animal     6.935000e+07      1000000.0      69.350000  

[8975 rows x 8 columns]

In [101]:
# Renommage de la table du ratio énergétique

ratio_kcal_final =  sorted_dm1_kcal_final.copy()

**R4.1 - Ratio "énergie/poids" en kcal/kg pour chaque pays et chaque produit**

In [102]:

print('\nTable du ratio "énergie/poids" en kcal/kg :"\n')

ratio_kcal_final


Table du ratio "énergie/poids" en kcal/kg :"



codePays                  pays  codeProduit                  produit  \
2931         40                 Chili         2586  Huil Plantes Oleif Autr   
11756       117   République de Corée         2582   Huile de Germe de Maïs   
11752       117   République de Corée         2572         Huile d'Arachide   
10925       171           Philippines         2580            Huile d'Olive   
3505         44              Colombie         2579          Huile de Sésame   
...         ...                   ...          ...                      ...   
14446       234               Uruguay         2612          Citrons & Limes   
12268       188  Saint-Kitts-et-Nevis         2611      Oranges, Mandarines   
7531         83              Kiribati         2611      Oranges, Mandarines   
12486       244                 Samoa         2612          Citrons & Limes   
12513       244                 Samoa         2767       Mollusques, Autres   

        origin  dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
2931   vegetal     1.929390e+10      1000000.0   19293.900000  
11756  vegetal     1.798100e+10      1000000.0   17980.995000  
11752  vegetal     1.798100e+10      1000000.0   17980.995000  
10925  vegetal     3.591381e+10      2000000.0   17956.905000  
3505   vegetal     1.763716e+10      1000000.0   17637.165000  
...        ...              ...            ...            ...  
14446  vegetal     1.243555e+09     15000000.0      82.903667  
12268  vegetal     7.884000e+07      1000000.0      78.840000  
7531   vegetal     7.446000e+07      1000000.0      74.460000  
12486  vegetal     6.935000e+07      1000000.0      69.350000  
12513   animal     6.935000e+07      1000000.0      69.350000  

[8975 rows x 8 columns]

**Table des ratios de  protéines**

In [103]:
# Création de la table des protéines 

dm2_prot = extract_data_merged[['codePays','pays','codeProduit','produit','origin','dispo_prot_kg','nourriture_kg']]

# Calcul du ratio protéines / masse

dm2_prot["ratio_prot"] = dm2_prot["dispo_prot_kg"] / dm2_prot["nourriture_kg"]
dm2_prot

codePays          pays  codeProduit                produit   origin  \
0             2   Afghanistan         2736       Abats Comestible   animal   
1             2   Afghanistan         2614        Agrumes, Autres  vegetal   
2             2   Afghanistan         2680  Aliments pour enfants  vegetal   
3             2   Afghanistan         2618                 Ananas  vegetal   
4             2   Afghanistan         2615                Bananes  vegetal   
...         ...           ...          ...                    ...      ...   
15600        25  Îles Salomon         2733       Viande de Suides   animal   
15601        25  Îles Salomon         2734    Viande de Volailles   animal   
15602        25  Îles Salomon         2735          Viande, Autre   animal   
15603        25  Îles Salomon         2655                    Vin  vegetal   
15604        25  Îles Salomon         2645         Épices, Autres  vegetal   

       dispo_prot_kg  nourriture_kg  ratio_prot  
0         8586639.60     53000000.0    0.162012  
1          223029.60     39000000.0    0.005719  
2          334544.40      2000000.0    0.167272  
3                NaN            0.0         NaN  
4          557574.00     82000000.0    0.006800  
...              ...            ...         ...  
15600      288718.65      3000000.0    0.096240  
15601      233432.10      2000000.0    0.116716  
15602        8190.60            0.0         inf  
15603            NaN            0.0         NaN  
15604       30714.75            0.0         inf  

[15605 rows x 8 columns]

In [104]:
# Remplacement des valeurs " infinies " par des NaN

dm2_prot = dm2_prot.replace([np.inf, -np.inf], np.nan)
dm2_prot_dropna = dm2_prot.dropna()
dm2_prot_p = dm2_prot_dropna[dm2_prot_dropna['ratio_prot']  != 0]
sorted_dm2_prot_final = dm2_prot_p.sort_values(by = ['ratio_prot'], ascending = False)

sorted_dm2_prot_final
ratio_prot_final = sorted_dm2_prot_final.copy()

**R4.2 - Ratio "protéines/poids total" pour chaque pays et chaque produit. Vérifier la cohérence de votre calcul en comparant ce ratio aux données disponibles sur internet, par exemple en cherchant la teneur en protéines de l'avoine**

In [105]:
print('\nRatio dispo_prot_kg/nourriture_kg\n')

ratio_prot_final


Ratio dispo_prot_kg/nourriture_kg



codePays         pays  codeProduit                 produit   origin  \
1968         20     Botswana         2555                    Soja  vegetal   
5808         91       Guyana         2555                    Soja  vegetal   
11066       173      Pologne         2555                    Soja  vegetal   
8676        133         Mali         2555                    Soja  vegetal   
1058         11     Autriche         2555                    Soja  vegetal   
...         ...          ...          ...                     ...      ...   
10461       235  Ouzbékistan         2575  Huile Graines de Coton  vegetal   
1470        255     Belgique         2737  Graisses Animales Crue   animal   
4416        203      Espagne         2573      Huile de Tournesol  vegetal   
2826         33       Canada         2543      Edulcorants Autres  vegetal   
8142        256   Luxembourg         2655                     Vin  vegetal   

       dispo_prot_kg  nourriture_kg  ratio_prot  
1968       885198.00      2000000.0    0.442599  
5808       423400.00      1000000.0    0.423400  
11066      836952.30      2000000.0    0.418476  
8676       781932.20      2000000.0    0.390966  
1058      6542424.25     17000000.0    0.384848  
...              ...            ...         ...  
10461      105609.10    219000000.0    0.000482  
1470        40529.60    120000000.0    0.000338  
4416       171283.55    564000000.0    0.000304  
2826       128414.30    534000000.0    0.000240  
8142         1934.50     27000000.0    0.000072  

[7851 rows x 8 columns]

** **

**Vérification avec les oeufs**

In [108]:
# Sélection des données relatives aux oeufs

oeufs = ratio_kcal_final[ratio_kcal_final["produit"] == "Oeufs"]
oeufs = oeufs[["codePays","pays", "produit", "ratio_kcal_kg"]]
oeufs

codePays                             pays produit  ratio_kcal_kg
11599       184                           Rwanda   Oeufs    2149.302500
11132        70              Polynésie française   Oeufs    1769.337500
11685        37        République centrafricaine   Oeufs    1684.840000
10022       153               Nouvelle-Calédonie   Oeufs    1635.200000
1219         12                          Bahamas   Oeufs    1582.457500
...         ...                              ...     ...            ...
2766         32                         Cameroun   Oeufs     902.523333
5787         91                           Guyana   Oeufs     876.000000
12349       191  Saint-Vincent-et-les Grenadines   Oeufs     795.700000
12435       189                     Sainte-Lucie   Oeufs     730.730000
12589       193             Sao Tomé-et-Principe   Oeufs     704.450000

[169 rows x 4 columns]

In [109]:
print("\nSelon Wikipédia, la valeur nutritionnele d'un oeuf est de 147 kcal pour 100g, soit 1470 kcal/kg")
print("\nMoyenne mondiale calculée du ratio énergie/masse pour les oeufs : {:.0f}".format(oeufs["ratio_kcal_kg"].mean()), "kcal/kg")


Selon Wikipédia, la valeur nutritionnele d'un oeuf est de 147 kcal pour 100g, soit 1470 kcal/kg

Moyenne mondiale calculée du ratio énergie/masse pour les oeufs : 1345 kcal/kg


** **

**Calcul du pourcentage de protéines de chaque produit (pour chaque pays). Ce pourcentage est obtenu en calculant le ratio "poids de protéines/poids total" (attention aux unités utilisées).**

In [110]:
# Création de la table des disponibilités alimentaires(de nourriture, en réalité)

dispo_alim_nourriture = extract_data_merged[['codePays', 'pays', 'codeProduit', 'produit', 'annee', 'origin', 'dispo_prot_kg', 'nourriture_kg']]

dispo_alim_nourriture

codePays          pays  codeProduit                produit  annee  \
0             2   Afghanistan         2736       Abats Comestible   2013   
1             2   Afghanistan         2614        Agrumes, Autres   2013   
2             2   Afghanistan         2680  Aliments pour enfants   2013   
3             2   Afghanistan         2618                 Ananas   2013   
4             2   Afghanistan         2615                Bananes   2013   
...         ...           ...          ...                    ...    ...   
15600        25  Îles Salomon         2733       Viande de Suides   2013   
15601        25  Îles Salomon         2734    Viande de Volailles   2013   
15602        25  Îles Salomon         2735          Viande, Autre   2013   
15603        25  Îles Salomon         2655                    Vin   2013   
15604        25  Îles Salomon         2645         Épices, Autres   2013   

        origin  dispo_prot_kg  nourriture_kg  
0       animal     8586639.60     53000000.0  
1      vegetal      223029.60     39000000.0  
2      vegetal      334544.40      2000000.0  
3      vegetal            NaN            0.0  
4      vegetal      557574.00     82000000.0  
...        ...            ...            ...  
15600   animal      288718.65      3000000.0  
15601   animal      233432.10      2000000.0  
15602   animal        8190.60            0.0  
15603  vegetal            NaN            0.0  
15604  vegetal       30714.75            0.0  

[15605 rows x 8 columns]

In [111]:
dispo_alim_nourriture['ratio_poids_protéines__poids_total_%'] = (dispo_alim_nourriture['dispo_prot_kg'] / dispo_alim_nourriture['nourriture_kg']) * 100
dispo_alim_nourriture = dispo_alim_nourriture.replace([np.inf, -np.inf], np.nan)
dispo_alim_nourriture = dispo_alim_nourriture.dropna()
dispo_alim_nourriture = dispo_alim_nourriture[dispo_alim_nourriture['ratio_poids_protéines__poids_total_%']  != 0]

**R4.2 - Pourcentage "poids de protéines/poids total"**

In [112]:
print('\nPourcentage de protéines par rapport à la nourriture dans chaque produit(pour chaque pays):\n')
dispo_alim_nourriture


Pourcentage de protéines par rapport à la nourriture dans chaque produit(pour chaque pays):



codePays          pays  codeProduit                produit  annee  \
0             2   Afghanistan         2736       Abats Comestible   2013   
1             2   Afghanistan         2614        Agrumes, Autres   2013   
2             2   Afghanistan         2680  Aliments pour enfants   2013   
4             2   Afghanistan         2615                Bananes   2013   
5             2   Afghanistan         2740           Beurre, Ghee   2013   
...         ...           ...          ...                    ...    ...   
15589        25  Îles Salomon         2534            Racines nda   2013   
15591        25  Îles Salomon         2805       Riz (Eq Blanchi)   2013   
15599        25  Îles Salomon         2731       Viande de Bovins   2013   
15600        25  Îles Salomon         2733       Viande de Suides   2013   
15601        25  Îles Salomon         2734    Viande de Volailles   2013   

        origin  dispo_prot_kg  nourriture_kg  \
0       animal     8586639.60     53000000.0   
1      vegetal      223029.60     39000000.0   
2      vegetal      334544.40      2000000.0   
4      vegetal      557574.00     82000000.0   
5       animal      334544.40     36000000.0   
...        ...            ...            ...   
15589  vegetal      751487.55     42000000.0   
15591  vegetal     2231938.50     36000000.0   
15599   animal      536484.30      3000000.0   
15600   animal      288718.65      3000000.0   
15601   animal      233432.10      2000000.0   

       ratio_poids_protéines__poids_total_%  
0                                 16.201207  
1                                  0.571871  
2                                 16.727220  
4                                  0.679968  
5                                  0.929290  
...                                     ...  
15589                              1.789256  
15591                              6.199829  
15599                             17.882810  
15600                              9.623955  
15601                             11.671605  

[7851 rows x 9 columns]

**Vérification avec l'avoine**

In [113]:
# Extraction des données relatives à l'avoine

avoine = dispo_alim_nourriture[dispo_alim_nourriture["produit"] == "Avoine"]
avoine = avoine[["codePays","pays", "produit", "ratio_poids_protéines__poids_total_%"]]
avoine

codePays                                    pays produit  \
67          202                          Afrique du Sud  Avoine   
347          79                               Allemagne  Avoine   
613         194                         Arabie saoudite  Avoine   
707           9                               Argentine  Avoine   
800           1                                 Arménie  Avoine   
...         ...                                     ...     ...   
14612       236  Venezuela (République bolivarienne du)  Avoine   
14788       249                                   Yémen  Avoine   
15252        58                                Équateur  Avoine   
15347       231                   États-Unis d'Amérique  Avoine   
15441       238                                Éthiopie  Avoine   

       ratio_poids_protéines__poids_total_%  
67                                 7.705296  
347                               11.412418  
613                                9.353409  
707                                8.404328  
800                                9.779445  
...                                     ...  
14612                              7.198589  
14788                              8.908555  
15252                              9.533210  
15347                              7.295392  
15441                             11.448955  

[91 rows x 4 columns]

In [114]:
print("Selon Wikipédia, la valeur nutritionnelle de l'avoine en protéines est de 10,7 %")
print("Moyenne mondiale calculée du ratio protéines / poids pour l'avoine : {:.1f}".format(avoine["ratio_poids_protéines__poids_total_%"].mean()), "%")

Selon Wikipédia, la valeur nutritionnelle de l'avoine en protéines est de 10,7 %
Moyenne mondiale calculée du ratio protéines / poids pour l'avoine : 8.4 %


** **

**Question 5 : Citez 5 aliments parmi les 20 aliments les plus caloriques en utilisant le ratio énergie/poids.**

**Q5.1 - 5 aliments parmi les 20 aliments les plus caloriques, en utilisant le ratio énergie/poids.**

In [115]:
# Rappel de la table des ratios énergétiques

ratio_kcal_final

codePays                  pays  codeProduit                  produit  \
2931         40                 Chili         2586  Huil Plantes Oleif Autr   
11756       117   République de Corée         2582   Huile de Germe de Maïs   
11752       117   République de Corée         2572         Huile d'Arachide   
10925       171           Philippines         2580            Huile d'Olive   
3505         44              Colombie         2579          Huile de Sésame   
...         ...                   ...          ...                      ...   
14446       234               Uruguay         2612          Citrons & Limes   
12268       188  Saint-Kitts-et-Nevis         2611      Oranges, Mandarines   
7531         83              Kiribati         2611      Oranges, Mandarines   
12486       244                 Samoa         2612          Citrons & Limes   
12513       244                 Samoa         2767       Mollusques, Autres   

        origin  dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
2931   vegetal     1.929390e+10      1000000.0   19293.900000  
11756  vegetal     1.798100e+10      1000000.0   17980.995000  
11752  vegetal     1.798100e+10      1000000.0   17980.995000  
10925  vegetal     3.591381e+10      2000000.0   17956.905000  
3505   vegetal     1.763716e+10      1000000.0   17637.165000  
...        ...              ...            ...            ...  
14446  vegetal     1.243555e+09     15000000.0      82.903667  
12268  vegetal     7.884000e+07      1000000.0      78.840000  
7531   vegetal     7.446000e+07      1000000.0      74.460000  
12486  vegetal     6.935000e+07      1000000.0      69.350000  
12513   animal     6.935000e+07      1000000.0      69.350000  

[8975 rows x 8 columns]

In [116]:
# Classement par ordre décroissant du ratio énergétique

sorted_Ratio_énergie_poids_pour_chaque_produit_en_kcal_kg = ratio_kcal_final.sort_values(by=['ratio_kcal_kg'], ascending = False)
table_ratio_nrj_poids = sorted_Ratio_énergie_poids_pour_chaque_produit_en_kcal_kg[['produit','ratio_kcal_kg']]
print("\n Les 20 aliments les plus caloriques en utilisant le ratio énergie/poids:\n") 
table_ratio_nrj_poids.head(20)


 Les 20 aliments les plus caloriques en utilisant le ratio énergie/poids:



produit  ratio_kcal_kg
2931   Huil Plantes Oleif Autr   19293.900000
11752         Huile d'Arachide   17980.995000
11756   Huile de Germe de Maïs   17980.995000
10925            Huile d'Olive   17956.905000
3505           Huile de Sésame   17637.165000
4405   Huil Plantes Oleif Autr   17128.355000
7337    Huile Graines de Coton   16189.210000
9093          Huile d'Arachide   14883.726667
282              Huile de Coco   14310.920000
11024   Huile de Germe de Maïs   13949.205000
12829            Huile d'Olive   13924.750000
13015       Huile de Palmistes   13856.860000
13000            Feve de Cacao   13856.860000
3307             Huile d'Olive   13668.431216
2390             Huile de Coco   13661.220000
10555      Huile de Son de Riz   13296.439000
3036        Huile de Tournesol   13147.300000
3035           Huile de Sésame   13147.300000
8083   Huil Plantes Oleif Autr   12961.150000
11577         Huile d'Arachide   12895.815000


**R5.1 - 5 aliments parmi les 20 les plus caloriques, en utilisant le ratio énergie/poids :**
    
* Huile de Palmistes 
* Huile de Sésame
* Huile Graines de Coton 
* Huile d'Olive
* Huile de Son de Riz


**Q5.2 Étonnamment, il arrive que ce ratio soit différent en fonction du pays. Il faudra donc réaliser pour chaque aliment une moyenne sur les différents pays**

In [117]:
#  Calcul du ratio pour la France par exemple

df_ratio_kcal_final = pd.DataFrame(ratio_kcal_final)

ratio_France = df_ratio_kcal_final.loc[df_ratio_kcal_final['pays'] == 'France']

# Classement des produits les caloriques pour la France

ratio_France.sort_values(by=['ratio_kcal_kg'], ascending=False).head(10)

codePays    pays  codeProduit                  produit   origin  \
4881        68  France         2579          Huile de Sésame  vegetal   
4871        68  France         2586  Huil Plantes Oleif Autr  vegetal   
4880        68  France         2571            Huile de Soja  vegetal   
4882        68  France         2573       Huile de Tournesol  vegetal   
4876        68  France         2574  Huile de Colza&Moutarde  vegetal   
4884        68  France         2781       Huiles de Poissons   animal   
4874        68  France         2580            Huile d'Olive  vegetal   
4878        68  France         2577           Huile de Palme  vegetal   
4877        68  France         2582   Huile de Germe de Maïs  vegetal   
4873        68  France         2572         Huile d'Arachide  vegetal   

      dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
4881     4.693243e+10      5000000.0    9386.486000  
4871     1.009047e+12    110000000.0    9173.156773  
4880     2.252757e+12    254000000.0    8869.120630  
4882     3.449534e+12    391000000.0    8822.336586  
4876     1.759966e+12    200000000.0    8799.830625  
4884     1.407973e+11     16000000.0    8799.830625  
4874     9.855810e+11    112000000.0    8799.830625  
4878     2.581284e+11     30000000.0    8604.278833  
4877     3.754594e+11     44000000.0    8533.169091  
4873     1.173311e+11     14000000.0    8380.791071

In [118]:
# Ratio Cuba
ratio_Cuba = df_ratio_kcal_final.loc[df_ratio_kcal_final['pays'] == 'Cuba']
ratio_Cuba.sort_values(by=['ratio_kcal_kg'], ascending=False).head(10)

codePays  pays  codeProduit                  produit   origin  \
3875        49  Cuba         2577           Huile de Palme  vegetal   
3877        49  Cuba         2571            Huile de Soja  vegetal   
3879        49  Cuba         2573       Huile de Tournesol  vegetal   
3868        49  Cuba         2586  Huil Plantes Oleif Autr  vegetal   
3866        49  Cuba         2737   Graisses Animales Crue   animal   
3846        49  Cuba         2740             Beurre, Ghee   animal   
3842        49  Cuba         2556   Arachides Decortiquees  vegetal   
3870        49  Cuba         2572         Huile d'Arachide  vegetal   
3888        49  Cuba         2745                     Miel  vegetal   
3912        49  Cuba         2805         Riz (Eq Blanchi)  vegetal   

      dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
3875     1.233627e+10      1000000.0   12336.270000  
3877     7.072795e+11     80000000.0    8840.993500  
3879     8.224180e+09      1000000.0    8224.180000  
3868     8.224180e+09      1000000.0    8224.180000  
3866     6.168135e+10      8000000.0    7710.168750  
3846     2.056045e+10      3000000.0    6853.483333  
3842     1.233627e+10      2000000.0    6168.135000  
3870     4.112090e+09      1000000.0    4112.090000  
3888     4.112090e+09      1000000.0    4112.090000  
3912     2.738652e+12    763000000.0    3589.321022

In [119]:
# Sélection d'attributs pertinents de la table des ratios énergétiques

selec = ratio_kcal_final[['pays','produit','ratio_kcal_kg']]
selec.head()

pays                  produit  ratio_kcal_kg
2931                 Chili  Huil Plantes Oleif Autr      19293.900
11756  République de Corée   Huile de Germe de Maïs      17980.995
11752  République de Corée         Huile d'Arachide      17980.995
10925          Philippines            Huile d'Olive      17956.905
3505              Colombie          Huile de Sésame      17637.165

In [120]:
# Calcul du ratio moyen sur les produits

ratio_moyen_énergie_poids_pour_chaque_produit_en_kcal_kg = selec.groupby('produit').mean()

# Nom plus parlant de la colonne des ratios

ratio_moyen_énergie_poids_pour_chaque_produit_en_kcal_kg.rename(columns = {'ratio_kcal_kg':'moyenne_ratio_énergie_poids_kcal_kg'}, inplace = True)

# Classement par ordre décroissant des ratios

sorted_ratio_moyen_énergie_poids_pour_chaque_produit_en_kcal_kg = ratio_moyen_énergie_poids_pour_chaque_produit_en_kcal_kg.sort_values(by = ['moyenne_ratio_énergie_poids_kcal_kg'], ascending = False)
print('\nTable du ratio moyen énergie/poids par produits\n')
sorted_ratio_moyen_énergie_poids_pour_chaque_produit_en_kcal_kg


Table du ratio moyen énergie/poids par produits



moyenne_ratio_énergie_poids_kcal_kg
produit                                                      
Huiles de Foie de Poisso                          9982.932500
Huile de Sésame                                   9433.744729
Huile de Son de Riz                               9361.549883
Huiles de Poissons                                9003.715504
Huile d'Arachide                                  8935.765811
...                                                       ...
Pamplemousse                                       249.847529
Agrumes, Autres                                    248.981045
Mollusques, Autres                                 241.661334
Tomates                                            206.074377
Citrons & Limes                                    194.021951

[94 rows x 1 columns]

**R5.2 - Classement de 5 aliments parmi les 20 aliments les plus caloriques, en fonction du ratio moyen énergie/poids:**
* 1 - Huiles de Foie de Poisso
* 2 - Huile de Sésame
* 3 - Huile de Son de Riz
* 4 - Huiles de Poissons
* 5 - Huile d'Arachide	

**Q5.3 - Citez 5 aliments parmi les 20 les plus riche en protéines**

In [121]:
# Sélection des attributs nécessaires

ratio_prot_prod = dispo_alim_nourriture[['produit','ratio_poids_protéines__poids_total_%']]

# Calcul du ratio moyen par produit

moyenne_sorted_ratio_prot_prod = ratio_prot_prod.groupby('produit').mean()
moyenne_sorted_ratio_prot_prod.rename(columns = {'ratio_poids_protéines__poids_total_%':'moyenne_ratio_poids_protéines__poids_total_%'},inplace = True)

sorted_ratio_prot_prod = round((moyenne_sorted_ratio_prot_prod),2).sort_values(by = ['moyenne_ratio_poids_protéines__poids_total_%'], ascending = False)

print('\nPourcentage de protéines dans chaque produit(pour chaque pays):\n')
sorted_ratio_prot_prod.head(20)


Pourcentage de protéines dans chaque produit(pour chaque pays):



moyenne_ratio_poids_protéines__poids_total_%
produit                                                               
Graines Colza/Moutarde                                           28.54
Soja                                                             28.53
Arachides Decortiquees                                           25.15
Pois                                                             22.32
Légumineuses Autres                                              21.97
Haricots                                                         21.55
Abats Comestible                                                 17.56
Sésame                                                           17.50
Viande, Autre                                                    17.40
Plantes Oleiferes, Autre                                         17.05
Aliments pour enfants                                            14.88
Viande de Bovins                                                 14.38
Cephalopodes                                                     13.99
Viande d'Ovins/Caprins                                           13.58
Viande de Volailles                                              12.62
Piments                                                          12.10
Poissons Pelagiques                                              11.93
Graines de tournesol                                             11.18
Poissons Marins, Autres                                          11.01
Épices, Autres                                                   10.74

**R5.3 : 5 aliments parmi les 20 les plus riches en protéines :**
* Graines Colza/Moutarde 
* Sésame
* Piments
* Pois
* Cephalopodes

** **




**Question 6 : Calculez, pour les produits végétaux uniquement, la disponibilité intérieure mondiale exprimée en kcal.**

In [122]:
# Sélection des disponibilités intérieures d'origine végétale

veg = extract_data_merged[["codePays","codeProduit","produit", "origin",'dispo_alim_kcal',"dispo_int"]]

veg_dispo_int_kcal = veg[veg["origin"] == 'vegetal']
veg_dispo_int_kcal

codePays  codeProduit                produit   origin  dispo_alim_kcal  \
1             2         2614        Agrumes, Autres  vegetal     1.115148e+10   
2             2         2680  Aliments pour enfants  vegetal     1.115148e+10   
3             2         2618                 Ananas  vegetal     0.000000e+00   
4             2         2615                Bananes  vegetal     4.460592e+10   
6             2         2656                  Bière  vegetal     0.000000e+00   
...         ...          ...                    ...      ...              ...   
15595        25         2561                 Sésame  vegetal     0.000000e+00   
15596        25         2635                    Thé  vegetal     0.000000e+00   
15597        25         2601                Tomates  vegetal     0.000000e+00   
15603        25         2655                    Vin  vegetal     0.000000e+00   
15604        25         2645         Épices, Autres  vegetal     8.190600e+08   

       dispo_int  
1           41.0  
2            2.0  
3            0.0  
4           82.0  
6            3.0  
...          ...  
15595        0.0  
15596        0.0  
15597        0.0  
15603        0.0  
15604        0.0  

[11896 rows x 6 columns]

In [123]:
# Fusion de la table de disponibilités végétales avec celle des ratios d'énergie

veg_concat_ratio = veg_dispo_int_kcal.merge(ratio_kcal_final, on = ["codePays","codeProduit"])
veg_concat_ratio

codePays  codeProduit              produit_x origin_x  \
0            2         2614        Agrumes, Autres  vegetal   
1            2         2680  Aliments pour enfants  vegetal   
2            2         2615                Bananes  vegetal   
3            2         2511                    Blé  vegetal   
4            2         2543     Edulcorants Autres  vegetal   
...        ...          ...                    ...      ...   
6679        25         2532                 Manioc  vegetal   
6680        25         2533         Patates douces  vegetal   
6681        25         2534            Racines nda  vegetal   
6682        25         2805       Riz (Eq Blanchi)  vegetal   
6683        25         2542          Sucre Eq Brut  vegetal   

      dispo_alim_kcal_x  dispo_int          pays              produit_y  \
0          1.115148e+10       41.0   Afghanistan        Agrumes, Autres   
1          1.115148e+10        2.0   Afghanistan  Aliments pour enfants   
2          4.460592e+10       82.0   Afghanistan                Bananes   
3          1.526638e+13     5992.0   Afghanistan                    Blé   
4          2.230296e+10       16.0   Afghanistan     Edulcorants Autres   
...                 ...        ...           ...                    ...   
6679       3.071475e+09        3.0  Îles Salomon                 Manioc   
6680       9.603478e+10      100.0  Îles Salomon         Patates douces   
6681       3.255764e+10       43.0  Îles Salomon            Racines nda   
6682       1.275686e+11       49.0  Îles Salomon       Riz (Eq Blanchi)   
6683       8.395365e+09        2.0  Îles Salomon          Sucre Eq Brut   

     origin_y  dispo_alim_kcal_y  nourriture_kg  ratio_kcal_kg  
0     vegetal       1.115148e+10   3.900000e+07     285.935385  
1     vegetal       1.115148e+10   2.000000e+06    5575.740000  
2     vegetal       4.460592e+10   8.200000e+07     543.974634  
3     vegetal       1.526638e+13   4.895000e+09    3118.769381  
4     vegetal       2.230296e+10   1.600000e+07    1393.935000  
...       ...                ...            ...            ...  
6679  vegetal       3.071475e+09   3.000000e+06    1023.825000  
6680  vegetal       9.603478e+10   9.800000e+07     979.946786  
6681  vegetal       3.255764e+10   4.200000e+07     775.181786  
6682  vegetal       1.275686e+11   3.600000e+07    3543.572083  
6683  vegetal       8.395365e+09   2.000000e+06    4197.682500  

[6684 rows x 12 columns]

In [124]:
# Renommage des colonnes

veg_concat_ratio.rename({'produit_x': 'produit','origin_x':'origin','dispo_alim_kcal_x':'dispo_alim_kcal' }, axis=1, inplace=True)

# Suppression des colonnes non nécessaires

del_cols = ['origin_y','dispo_alim_kcal_y']

veg_concat_ratio.drop(del_cols, axis=1, inplace = True)
veg_concat_ratio

codePays  codeProduit                produit   origin  dispo_alim_kcal  \
0            2         2614        Agrumes, Autres  vegetal     1.115148e+10   
1            2         2680  Aliments pour enfants  vegetal     1.115148e+10   
2            2         2615                Bananes  vegetal     4.460592e+10   
3            2         2511                    Blé  vegetal     1.526638e+13   
4            2         2543     Edulcorants Autres  vegetal     2.230296e+10   
...        ...          ...                    ...      ...              ...   
6679        25         2532                 Manioc  vegetal     3.071475e+09   
6680        25         2533         Patates douces  vegetal     9.603478e+10   
6681        25         2534            Racines nda  vegetal     3.255764e+10   
6682        25         2805       Riz (Eq Blanchi)  vegetal     1.275686e+11   
6683        25         2542          Sucre Eq Brut  vegetal     8.395365e+09   

      dispo_int          pays              produit_y  nourriture_kg  \
0          41.0   Afghanistan        Agrumes, Autres   3.900000e+07   
1           2.0   Afghanistan  Aliments pour enfants   2.000000e+06   
2          82.0   Afghanistan                Bananes   8.200000e+07   
3        5992.0   Afghanistan                    Blé   4.895000e+09   
4          16.0   Afghanistan     Edulcorants Autres   1.600000e+07   
...         ...           ...                    ...            ...   
6679        3.0  Îles Salomon                 Manioc   3.000000e+06   
6680      100.0  Îles Salomon         Patates douces   9.800000e+07   
6681       43.0  Îles Salomon            Racines nda   4.200000e+07   
6682       49.0  Îles Salomon       Riz (Eq Blanchi)   3.600000e+07   
6683        2.0  Îles Salomon          Sucre Eq Brut   2.000000e+06   

      ratio_kcal_kg  
0        285.935385  
1       5575.740000  
2        543.974634  
3       3118.769381  
4       1393.935000  
...             ...  
6679    1023.825000  
6680     979.946786  
6681     775.181786  
6682    3543.572083  
6683    4197.682500  

[6684 rows x 10 columns]

In [125]:
# Réorganisation des colonnes pour faciliter la lisibilité

veg_concat_ratio_reorg = veg_concat_ratio[['codePays','pays','codeProduit','produit','dispo_int','dispo_alim_kcal','nourriture_kg','ratio_kcal_kg']]
veg_concat_ratio_reorg

codePays          pays  codeProduit                produit  dispo_int  \
0            2   Afghanistan         2614        Agrumes, Autres       41.0   
1            2   Afghanistan         2680  Aliments pour enfants        2.0   
2            2   Afghanistan         2615                Bananes       82.0   
3            2   Afghanistan         2511                    Blé     5992.0   
4            2   Afghanistan         2543     Edulcorants Autres       16.0   
...        ...           ...          ...                    ...        ...   
6679        25  Îles Salomon         2532                 Manioc        3.0   
6680        25  Îles Salomon         2533         Patates douces      100.0   
6681        25  Îles Salomon         2534            Racines nda       43.0   
6682        25  Îles Salomon         2805       Riz (Eq Blanchi)       49.0   
6683        25  Îles Salomon         2542          Sucre Eq Brut        2.0   

      dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
0        1.115148e+10   3.900000e+07     285.935385  
1        1.115148e+10   2.000000e+06    5575.740000  
2        4.460592e+10   8.200000e+07     543.974634  
3        1.526638e+13   4.895000e+09    3118.769381  
4        2.230296e+10   1.600000e+07    1393.935000  
...               ...            ...            ...  
6679     3.071475e+09   3.000000e+06    1023.825000  
6680     9.603478e+10   9.800000e+07     979.946786  
6681     3.255764e+10   4.200000e+07     775.181786  
6682     1.275686e+11   3.600000e+07    3543.572083  
6683     8.395365e+09   2.000000e+06    4197.682500  

[6684 rows x 8 columns]

In [126]:
# Conversion de la disponibilité intérieure en kcal

veg_concat_ratio_reorg["dispo_int_kcal"] = veg_concat_ratio_reorg["dispo_int"] * 1000000 * veg_concat_ratio_reorg["ratio_kcal_kg"]
veg_concat_ratio_reorg

codePays          pays  codeProduit                produit  dispo_int  \
0            2   Afghanistan         2614        Agrumes, Autres       41.0   
1            2   Afghanistan         2680  Aliments pour enfants        2.0   
2            2   Afghanistan         2615                Bananes       82.0   
3            2   Afghanistan         2511                    Blé     5992.0   
4            2   Afghanistan         2543     Edulcorants Autres       16.0   
...        ...           ...          ...                    ...        ...   
6679        25  Îles Salomon         2532                 Manioc        3.0   
6680        25  Îles Salomon         2533         Patates douces      100.0   
6681        25  Îles Salomon         2534            Racines nda       43.0   
6682        25  Îles Salomon         2805       Riz (Eq Blanchi)       49.0   
6683        25  Îles Salomon         2542          Sucre Eq Brut        2.0   

      dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  dispo_int_kcal  
0        1.115148e+10   3.900000e+07     285.935385    1.172335e+10  
1        1.115148e+10   2.000000e+06    5575.740000    1.115148e+10  
2        4.460592e+10   8.200000e+07     543.974634    4.460592e+10  
3        1.526638e+13   4.895000e+09    3118.769381    1.868767e+13  
4        2.230296e+10   1.600000e+07    1393.935000    2.230296e+10  
...               ...            ...            ...             ...  
6679     3.071475e+09   3.000000e+06    1023.825000    3.071475e+09  
6680     9.603478e+10   9.800000e+07     979.946786    9.799468e+10  
6681     3.255764e+10   4.200000e+07     775.181786    3.333282e+10  
6682     1.275686e+11   3.600000e+07    3543.572083    1.736350e+11  
6683     8.395365e+09   2.000000e+06    4197.682500    8.395365e+09  

[6684 rows x 9 columns]

In [127]:
# Vérification des NaN et des valeurs nulles

print("Nombre de valeurs dans la table :", len(veg_concat_ratio_reorg.index))
print("Nombre de NaN dans la table:", veg_concat_ratio_reorg["dispo_int_kcal"].isna().sum())
print("Nombre de valeurs nulles dans la table :", len(veg_concat_ratio_reorg[veg_concat_ratio_reorg["dispo_int_kcal"] == 0].index))

# Sélection des valeurs non nulles

dispo_int_veg_kcal = veg_concat_ratio_reorg[veg_concat_ratio_reorg["dispo_int_kcal"] != 0]
print("\nNombre de valeur dans la table 'dispo_int_veg_kcal' après nettoyage :", len(dispo_int_veg_kcal.index))

Nombre de valeurs dans la table : 6684
Nombre de NaN dans la table: 0
Nombre de valeurs nulles dans la table : 3

Nombre de valeur dans la table 'dispo_int_veg_kcal' après nettoyage : 6681


In [128]:
print("\nDisponibilité intérieure mondiale de produits d'origine végétale : {:.2E} kcal".format(veg_concat_ratio_reorg["dispo_int_kcal"].sum()))


Disponibilité intérieure mondiale de produits d'origine végétale : 1.23E+16 kcal


**R6 - Disponibilité intérieure mondiale pour les végétaux :1.23E+16 kcal**

** **

**Question 7 : Combien d'humains pourraient être nourris si toute la disponibilité intérieure mondiale de produits végétaux était utilisée pour de la nourriture ? 
Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.**

**Pour les kcal**

In [129]:
# Sachant qu'un individu moyen consomme environ 2400 calories par jour, combien d'être humains peuvent être nourris avec l'énergie disponible?

besoin_kcal_p = 2400 * 365

nb_hbts = dispo_int_veg_kcal["dispo_int_kcal"].sum() / besoin_kcal_p

print("\nDisponibilité intérieure mondiale en énergie de produits d'origine végétale en nombre d'humains : {}\n".format(nb_hbts))


Disponibilité intérieure mondiale en énergie de produits d'origine végétale en nombre d'humains : 14054898704.501457



In [130]:
# Population potentielle rapportée à la population mondiale en 2013

print("\nProportion d\'humains susceptibles d\'être nourris par rapport à 2013 : {:.1f}".format(nb_hbts / pop["nb_habitants"].sum() * 100), "%")


Proportion d'humains susceptibles d'être nourris par rapport à 2013 : 200.9 %


**Pour les protéines**

In [131]:
# Extraction de la table des données de protéines végétales

veg_prot = extract_data_merged[["codePays","codeProduit","produit", "origin",'dispo_prot_kg',"dispo_int"]]
veg_prot

codePays  codeProduit                produit   origin  dispo_prot_kg  \
0             2         2736       Abats Comestible   animal     8586639.60   
1             2         2614        Agrumes, Autres  vegetal      223029.60   
2             2         2680  Aliments pour enfants  vegetal      334544.40   
3             2         2618                 Ananas  vegetal            NaN   
4             2         2615                Bananes  vegetal      557574.00   
...         ...          ...                    ...      ...            ...   
15600        25         2733       Viande de Suides   animal      288718.65   
15601        25         2734    Viande de Volailles   animal      233432.10   
15602        25         2735          Viande, Autre   animal        8190.60   
15603        25         2655                    Vin  vegetal            NaN   
15604        25         2645         Épices, Autres  vegetal       30714.75   

       dispo_int  
0           53.0  
1           41.0  
2            2.0  
3            0.0  
4           82.0  
...          ...  
15600        3.0  
15601        2.0  
15602        0.0  
15603        0.0  
15604        0.0  

[15605 rows x 6 columns]

In [132]:
# Jointure avec le table des ratios de protéines

veg_concat_ratio_prot = veg_prot.merge(ratio_prot_final, on = ["codePays","codeProduit"])
veg_concat_ratio_prot

codePays  codeProduit              produit_x origin_x  dispo_prot_kg_x  \
0            2         2736       Abats Comestible   animal       8586639.60   
1            2         2614        Agrumes, Autres  vegetal        223029.60   
2            2         2680  Aliments pour enfants  vegetal        334544.40   
3            2         2615                Bananes  vegetal        557574.00   
4            2         2740           Beurre, Ghee   animal        334544.40   
...        ...          ...                    ...      ...              ...   
7846        25         2534            Racines nda  vegetal        751487.55   
7847        25         2805       Riz (Eq Blanchi)  vegetal       2231938.50   
7848        25         2731       Viande de Bovins   animal        536484.30   
7849        25         2733       Viande de Suides   animal        288718.65   
7850        25         2734    Viande de Volailles   animal        233432.10   

      dispo_int          pays              produit_y origin_y  \
0          53.0   Afghanistan       Abats Comestible   animal   
1          41.0   Afghanistan        Agrumes, Autres  vegetal   
2           2.0   Afghanistan  Aliments pour enfants  vegetal   
3          82.0   Afghanistan                Bananes  vegetal   
4          36.0   Afghanistan           Beurre, Ghee   animal   
...         ...           ...                    ...      ...   
7846       43.0  Îles Salomon            Racines nda  vegetal   
7847       49.0  Îles Salomon       Riz (Eq Blanchi)  vegetal   
7848        3.0  Îles Salomon       Viande de Bovins   animal   
7849        3.0  Îles Salomon       Viande de Suides   animal   
7850        2.0  Îles Salomon    Viande de Volailles   animal   

      dispo_prot_kg_y  nourriture_kg  ratio_prot  
0          8586639.60     53000000.0    0.162012  
1           223029.60     39000000.0    0.005719  
2           334544.40      2000000.0    0.167272  
3           557574.00     82000000.0    0.006800  
4           334544.40     36000000.0    0.009293  
...               ...            ...         ...  
7846        751487.55     42000000.0    0.017893  
7847       2231938.50     36000000.0    0.061998  
7848        536484.30      3000000.0    0.178828  
7849        288718.65      3000000.0    0.096240  
7850        233432.10      2000000.0    0.116716  

[7851 rows x 12 columns]

In [133]:
# Correction de la table issue de la fusion

veg_concat_ratio_prot.rename({'produit_x':'produit','dispo_prot_kg_x': 'dispo_prot_kg','origin_x':'origin'}, axis=1, inplace=True)

del_cols = ['produit_y','origin_y','dispo_prot_kg_y']

veg_concat_ratio_prot.drop(del_cols, axis=1, inplace = True)
veg_concat_ratio_prot

codePays  codeProduit                produit   origin  dispo_prot_kg  \
0            2         2736       Abats Comestible   animal     8586639.60   
1            2         2614        Agrumes, Autres  vegetal      223029.60   
2            2         2680  Aliments pour enfants  vegetal      334544.40   
3            2         2615                Bananes  vegetal      557574.00   
4            2         2740           Beurre, Ghee   animal      334544.40   
...        ...          ...                    ...      ...            ...   
7846        25         2534            Racines nda  vegetal      751487.55   
7847        25         2805       Riz (Eq Blanchi)  vegetal     2231938.50   
7848        25         2731       Viande de Bovins   animal      536484.30   
7849        25         2733       Viande de Suides   animal      288718.65   
7850        25         2734    Viande de Volailles   animal      233432.10   

      dispo_int          pays  nourriture_kg  ratio_prot  
0          53.0   Afghanistan     53000000.0    0.162012  
1          41.0   Afghanistan     39000000.0    0.005719  
2           2.0   Afghanistan      2000000.0    0.167272  
3          82.0   Afghanistan     82000000.0    0.006800  
4          36.0   Afghanistan     36000000.0    0.009293  
...         ...           ...            ...         ...  
7846       43.0  Îles Salomon     42000000.0    0.017893  
7847       49.0  Îles Salomon     36000000.0    0.061998  
7848        3.0  Îles Salomon      3000000.0    0.178828  
7849        3.0  Îles Salomon      3000000.0    0.096240  
7850        2.0  Îles Salomon      2000000.0    0.116716  

[7851 rows x 9 columns]

In [134]:
# Vérification des NaN et des valeurs nulles

print("\nNombre de valeurs dans la table :", len(veg_concat_ratio_prot.index))
print("Nombre de NaN dans la table:", veg_concat_ratio_prot["dispo_prot_kg"].isna().sum())
print("Nombre de valeurs nulles dans la table :",len(veg_concat_ratio_prot[veg_concat_ratio_prot["dispo_prot_kg"] == 0].index))

dispo_int_veg_prot = veg_concat_ratio_prot[veg_concat_ratio_prot["dispo_prot_kg"] != 0]


Nombre de valeurs dans la table : 7851
Nombre de NaN dans la table: 0
Nombre de valeurs nulles dans la table : 0


In [135]:
print("\nDisponibilité intérieure mondiale de produits d'origine végétale : {:.2E}".format(dispo_int_veg_prot["dispo_prot_kg"].sum()), "kg de protéines\n")


Disponibilité intérieure mondiale de produits d'origine végétale : 2.07E+11 kg de protéines



In [136]:
# Un individu ordinaire a un besoin quotidien moyen de 0.060 kg de protéines 

besoin_prot_p = 0.060 * 365 # par an
nb_hbts = dispo_int_veg_prot["dispo_prot_kg"].sum() / besoin_prot_p

print("\nDisponibilité intérieure mondiale en protéines de produits d'origine végétale en nombre d'humains :{:.2E}".format(nb_hbts))
print("\nProportion d\'humains susceptibles d\'être nourris par rapport à 2013 : {:.1f}".format(nb_hbts / pop["nb_habitants"].sum() * 100), "%")


Disponibilité intérieure mondiale en protéines de produits d'origine végétale en nombre d'humains :9.46E+09

Proportion d'humains susceptibles d'être nourris par rapport à 2013 : 135.2 %


** **

**Question 8 : Combien d'humains pourraient être nourris si toute la disponibilité alimentaire en produits végétaux la nourriture végétale destinée aux animaux et les pertes de produits végétaux étaient utilisés pour de la nourriture ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.**

In [137]:
# Extraction des données utiles depuis la table de base

dispo_alim_veg_anim = data_merged[["pays", "codePays", "produit", "codeProduit", "origin", "alim_ani", "nourriture", "pertes"]]

# Sélection des produits végétaux

dispo_alim_veg = dispo_alim_veg_anim[dispo_alim_veg_anim["origin"] == "vegetal"]
dispo_alim_veg.head()

pays  codePays                produit  codeProduit   origin  \
1  Afghanistan         2        Agrumes, Autres         2614  vegetal   
2  Afghanistan         2  Aliments pour enfants         2680  vegetal   
3  Afghanistan         2                 Ananas         2618  vegetal   
4  Afghanistan         2                Bananes         2615  vegetal   
6  Afghanistan         2                  Bière         2656  vegetal   

   alim_ani  nourriture  pertes  
1       NaN        39.0     2.0  
2       NaN         2.0     NaN  
3       NaN         0.0     NaN  
4       NaN        82.0     NaN  
6       NaN         3.0     NaN

In [138]:
# Jointure avec la table des données d'énergie

dispo_alim_veg_kcal = dispo_alim_veg.merge(ratio_kcal_final, on=["pays","codePays", "codeProduit", "produit", "origin"])
dispo_alim_veg_kcal.head()

pays  codePays                produit  codeProduit   origin  \
0  Afghanistan         2        Agrumes, Autres         2614  vegetal   
1  Afghanistan         2  Aliments pour enfants         2680  vegetal   
2  Afghanistan         2                Bananes         2615  vegetal   
3  Afghanistan         2                    Blé         2511  vegetal   
4  Afghanistan         2     Edulcorants Autres         2543  vegetal   

   alim_ani  nourriture  pertes  dispo_alim_kcal  nourriture_kg  ratio_kcal_kg  
0       NaN        39.0     2.0     1.115148e+10   3.900000e+07     285.935385  
1       NaN         2.0     NaN     1.115148e+10   2.000000e+06    5575.740000  
2       NaN        82.0     NaN     4.460592e+10   8.200000e+07     543.974634  
3       NaN      4895.0   775.0     1.526638e+13   4.895000e+09    3118.769381  
4       NaN        16.0     NaN     2.230296e+10   1.600000e+07    1393.935000

In [139]:
# Poids total "alim_ani", "nourriture" et "pertes" et conversion des pertes en kg 

dispo_alim_veg_kcal["poids_total_kg"] = dispo_alim_veg_kcal["alim_ani"] + dispo_alim_veg_kcal["nourriture"] + dispo_alim_veg_kcal["pertes"] * 1000000
dispo_alim_veg_kcal.head()

pays  codePays                produit  codeProduit   origin  \
0  Afghanistan         2        Agrumes, Autres         2614  vegetal   
1  Afghanistan         2  Aliments pour enfants         2680  vegetal   
2  Afghanistan         2                Bananes         2615  vegetal   
3  Afghanistan         2                    Blé         2511  vegetal   
4  Afghanistan         2     Edulcorants Autres         2543  vegetal   

   alim_ani  nourriture  pertes  dispo_alim_kcal  nourriture_kg  \
0       NaN        39.0     2.0     1.115148e+10   3.900000e+07   
1       NaN         2.0     NaN     1.115148e+10   2.000000e+06   
2       NaN        82.0     NaN     4.460592e+10   8.200000e+07   
3       NaN      4895.0   775.0     1.526638e+13   4.895000e+09   
4       NaN        16.0     NaN     2.230296e+10   1.600000e+07   

   ratio_kcal_kg  poids_total_kg  
0     285.935385             NaN  
1    5575.740000             NaN  
2     543.974634             NaN  
3    3118.769381             NaN  
4    1393.935000             NaN

In [140]:
# Remplacement des NaN par 0.

dispo_alim_veg_kcal = dispo_alim_veg_kcal.fillna(0.)

# Somme des valeurs "alim_ani", "nourriture" et "pertes" et conversion milliers de tonnes en kg 

dispo_alim_veg_kcal["poids_total_kg"] = (dispo_alim_veg_kcal["alim_ani"] + dispo_alim_veg_kcal["nourriture"] + dispo_alim_veg_kcal["pertes"]) * 1000000

# Equivalent énergétique de la masse d'aliments

dispo_alim_veg_kcal["total_kcal"] = dispo_alim_veg_kcal["poids_total_kg"] * dispo_alim_veg_kcal["ratio_kcal_kg"]

In [141]:
# Calcul du nombre d'humains

nb_hbts = dispo_alim_veg_kcal["total_kcal"].sum() / besoin_kcal_p

print("\nDisponibilité cumulée (nourriture, pertes, alim_ani) mondiale en énergie de produits d'origine végétale en nombre d'humains : {:.2E}".format(nb_hbts))
print("Soit :{:.2f} % de la population mondiale de 2013".format(nb_hbts / pop["nb_habitants"].sum() * 100))


Disponibilité cumulée (nourriture, pertes, alim_ani) mondiale en énergie de produits d'origine végétale en nombre d'humains : 1.05E+10
Soit :149.65 % de la population mondiale de 2013


**Protéines**

In [142]:
# Poids total "alim_ani", "nourriture" et "pertes" et conversion des pertes en kg 

dispo_alim_veg_kcal.head()

pays  codePays                produit  codeProduit   origin  \
0  Afghanistan         2        Agrumes, Autres         2614  vegetal   
1  Afghanistan         2  Aliments pour enfants         2680  vegetal   
2  Afghanistan         2                Bananes         2615  vegetal   
3  Afghanistan         2                    Blé         2511  vegetal   
4  Afghanistan         2     Edulcorants Autres         2543  vegetal   

   alim_ani  nourriture  pertes  dispo_alim_kcal  nourriture_kg  \
0       0.0        39.0     2.0     1.115148e+10   3.900000e+07   
1       0.0         2.0     0.0     1.115148e+10   2.000000e+06   
2       0.0        82.0     0.0     4.460592e+10   8.200000e+07   
3       0.0      4895.0   775.0     1.526638e+13   4.895000e+09   
4       0.0        16.0     0.0     2.230296e+10   1.600000e+07   

   ratio_kcal_kg  poids_total_kg    total_kcal  
0     285.935385    4.100000e+07  1.172335e+10  
1    5575.740000    2.000000e+06  1.115148e+10  
2     543.974634    8.200000e+07  4.460592e+10  
3    3118.769381    5.670000e+09  1.768342e+13  
4    1393.935000    1.600000e+07  2.230296e+10

In [143]:
# Jointure avec la table des données de protéines

dispo_alim_veg_prot = dispo_alim_veg.merge(ratio_prot_final, on=["pays","codePays", "codeProduit", "produit", "origin"])
dispo_alim_veg_prot

pays  codePays                produit  codeProduit   origin  \
0      Afghanistan         2        Agrumes, Autres         2614  vegetal   
1      Afghanistan         2  Aliments pour enfants         2680  vegetal   
2      Afghanistan         2                Bananes         2615  vegetal   
3      Afghanistan         2                    Blé         2511  vegetal   
4      Afghanistan         2          Feve de Cacao         2633  vegetal   
...            ...       ...                    ...          ...      ...   
5392  Îles Salomon        25    Légumineuses Autres         2549  vegetal   
5393  Îles Salomon        25                 Manioc         2532  vegetal   
5394  Îles Salomon        25         Patates douces         2533  vegetal   
5395  Îles Salomon        25            Racines nda         2534  vegetal   
5396  Îles Salomon        25       Riz (Eq Blanchi)         2805  vegetal   

      alim_ani  nourriture  pertes  dispo_prot_kg  nourriture_kg  ratio_prot  
0          NaN        39.0     2.0   2.230296e+05   3.900000e+07    0.005719  
1          NaN         2.0     NaN   3.345444e+05   2.000000e+06    0.167272  
2          NaN        82.0     NaN   5.575740e+05   8.200000e+07    0.006800  
3          NaN      4895.0   775.0   4.116011e+08   4.895000e+09    0.084086  
4          NaN         1.0     NaN   1.115148e+05   1.000000e+06    0.111515  
...        ...         ...     ...            ...            ...         ...  
5392       NaN         6.0     0.0   1.314591e+06   6.000000e+06    0.219099  
5393       0.0         3.0     0.0   2.457180e+04   3.000000e+06    0.008191  
5394       NaN        98.0     2.0   9.808243e+05   9.800000e+07    0.010008  
5395       NaN        42.0     1.0   7.514875e+05   4.200000e+07    0.017893  
5396       0.0        36.0     1.0   2.231938e+06   3.600000e+07    0.061998  

[5397 rows x 11 columns]

In [144]:
# Remplacement des NaN par 0.

dispo_alim_veg_prot = dispo_alim_veg_prot.fillna(0.)

# Somme des valeurs "alim_ani", "nourriture" et "pertes" + conversion milliers de tonnes en kg 

dispo_alim_veg_prot["poids_total_kg"] = (dispo_alim_veg_prot["alim_ani"] + dispo_alim_veg_prot["nourriture"] + dispo_alim_veg_prot["pertes"]) * 1000000

# Equivalent énergétique de la masse d'aliments

dispo_alim_veg_prot["total_prot"] = dispo_alim_veg_prot["poids_total_kg"] * dispo_alim_veg_prot["ratio_prot"]
 
# Nettoyage des NaN

dispo_alim_veg_prot = dispo_alim_veg_prot.dropna()

# Calcul du nombre d'humains (rappel : 0,060 kg de protéines / personne)

nb_hbts = dispo_alim_veg_prot["total_prot"].sum() / besoin_prot_p

print("\nDisponibilité cumulée (nourriture, pertes, alim_ani) mondiale en protéines de produits d'origine végétale en nombre d'humains : {:.2E}".format(nb_hbts))
print("Pourcentage de la population mondiale : {:.1f}".format(nb_hbts / pop["nb_habitants"].sum() * 100), "%")


Disponibilité cumulée (nourriture, pertes, alim_ani) mondiale en protéines de produits d'origine végétale en nombre d'humains : 9.30E+09
Pourcentage de la population mondiale : 132.9 %


** **

**Question 9 : Combien d'humains pourraient être nourris avec la disponibilité alimentaire mondiale ? Donnez les résultats en termes de calories, puis de protéines, et exprimez ensuite ces 2 résultats en pourcentage de la population mondiale.**

**Pour les énergies**

In [145]:
# Nombre d'humains

nb_hbts = extract_data_merged["dispo_alim_kcal"].sum() / besoin_kcal_p

print("\nEquivalent en en nombre d'humains de toute la disponibilité alimentaire mondiale(animaux+végétaux) en énergie : {:.2E}".format(nb_hbts))
print("Soit {:.1f} % de la population mondiale en 2013".format(nb_hbts / pop["nb_habitants"].sum() * 100))


Equivalent en en nombre d'humains de toute la disponibilité alimentaire mondiale(animaux+végétaux) en énergie : 8.41E+09
Soit 120.1 % de la population mondiale en 2013


**Pour les protéines**

In [146]:
# Nombre d'humains (rappel : 0,060 kg / personne)

nb_hbts = extract_data_merged["dispo_prot_kg"].sum() / besoin_prot_p

print("\nEquivalent en en nombre d'humains de toute la disponibilité alimentaire mondiale(animaux+végétaux) en énergie : {:.2E}".format(nb_hbts))
print("Soit {:.1f}% de la population mondiale en 2013".format(nb_hbts / pop["nb_habitants"].sum() * 100))


Equivalent en en nombre d'humains de toute la disponibilité alimentaire mondiale(animaux+végétaux) en énergie : 9.46E+09
Soit 135.3% de la population mondiale en 2013


** **

**Question 10 : A partir des données téléchargées qui concernent la sous-nutrition, répondez à cette question : Quelle proportion de la population mondiale est considérée comme étant en sous-nutrition ?**

In [147]:
# Extraction des données de 2013

sous_nutrition = sous_alimentation.loc[(sous_alimentation['Description du Symbole'] == 'Estimation FAO')&(sous_alimentation['Année'] == '2012-2014')]

# Remplacement des valeurs <0,1 par 0,05 et conversion du type en nombres décimaux

sous_nutrition["Valeur"] = sous_nutrition["Valeur"].replace("<0.1", "0.05").astype(float)

# Calcul de la valeur réelle du nombre d'habitants et suppression du champs 'Valeur'

sous_nutrition['nb_personnes'] = sous_nutrition['Valeur'] * 1000000

# Suppression de la variable originelle 'Valeur'

del_col = ['Valeur','Unité']
sous_nutrition.drop(del_col, axis = 1, inplace = True)

# sous_nutrition.to_csv(resPath+'sous_nut.csv')

In [148]:
# Nombre total de sous-alimentés

nb_sous_nut = sous_nutrition['nb_personnes'].sum()

pop_monde = population['valeur'].sum() * 1000
prop_pop_sous_nut =  round((nb_sous_nut/pop_monde)*100,2)
print("\nPopulation mondiale : {} d'habitants".format(pop_monde))
print("Population considérée comme étant en sous-nutrition par la FAO : {} d'habitants".format(nb_sous_nut))
print("Proportion de personnes considérées comme étant en sous-nutrition par la FAO : {}% d'habitants".format(prop_pop_sous_nut))


Population mondiale : 6997326000 d'habitants
Population considérée comme étant en sous-nutrition par la FAO : 882550000.0 d'habitants
Proportion de personnes considérées comme étant en sous-nutrition par la FAO : 12.61% d'habitants


**R-10 - Proportion de la population mondiale considérée comme étant en sous-nutrition : 12.61 %**

** **

**Question 11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), quelle proportion (en termes de poids) est destinée à l'alimentation animale ?**

In [149]:
produit_cereales = cereales[['Code Produit','Produit']]
produit_cereales

Code Produit           Produit
0            2511               Blé
1            2805  Riz (Eq Blanchi)
2            2513              Orge
3            2514              Maïs
4            2517            Millet
..            ...               ...
886          2514              Maïs
887          2516            Avoine
888          2517            Millet
889          2518            Sorgho
890          2520  Céréales, Autres

[891 rows x 2 columns]

In [150]:
# Table temporaire qui va servir pour la fusion avec la table des céréales

data_merged_cereales = data_merged.copy()
data_merged_cereales.head(2)

pays  codePays  annee           produit  codeProduit   origin  \
0  Afghanistan         2   2013  Abats Comestible         2736   animal   
1  Afghanistan         2   2013   Agrumes, Autres         2614  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   

   dispo_int  export  import  nourriture  pertes  production  semences  \
0       53.0     NaN     NaN        53.0     NaN        53.0       NaN   
1       41.0     2.0    40.0        39.0     2.0         3.0       NaN   

   transfo  var_stock  nb_habitants  
0      NaN        NaN      30552000  
1      NaN        NaN      30552000  

[2 rows x 22 columns]

In [151]:
# Sélection des colonnes approppriées à partir de la table globale

data_merged_cereales_extract = data_merged_cereales[['codePays','pays','codeProduit','produit','alim_ani','nourriture','annee','origin']]
data_merged_cereales_extract.head(2)

codePays         pays  codeProduit           produit  alim_ani  nourriture  \
0         2  Afghanistan         2736  Abats Comestible       NaN        53.0   
1         2  Afghanistan         2614   Agrumes, Autres       NaN        39.0   

   annee   origin  
0   2013   animal  
1   2013  vegetal

In [152]:
# Construction de la colonne "is_cereale" et ajout à la table data_merged_cereales_extract

def set_cereal(row):
    if (   row["produit"] == "Blé" 
        or row["produit"] == "Orge" 
        or row["produit"] == 'Riz (Eq Blanchi)' 
        or row["produit"] == 'Maïs' 
        or row["produit"] == 'Seigle' 
        or row["produit"] == 'Avoine' 
        or row["produit"] == 'Sorgho' 
        or row["produit"] == 'Millet' 
        or row["produit"] == 'Céréales, Autres'):
        return "OUI"
    else:
        return "NON"

dm_cereales = data_merged_cereales_extract.assign(is_cereal=data_merged_cereales_extract.apply(set_cereal, axis=1))

In [153]:
print('\nTable des produits céréaliers(ou pas) suivant les pays:\n')
dm_cereales.head()


Table des produits céréaliers(ou pas) suivant les pays:



codePays         pays  codeProduit                produit  alim_ani  \
0         2  Afghanistan         2736       Abats Comestible       NaN   
1         2  Afghanistan         2614        Agrumes, Autres       NaN   
2         2  Afghanistan         2680  Aliments pour enfants       NaN   
3         2  Afghanistan         2618                 Ananas       NaN   
4         2  Afghanistan         2615                Bananes       NaN   

   nourriture  annee   origin is_cereal  
0        53.0   2013   animal       NON  
1        39.0   2013  vegetal       NON  
2         2.0   2013  vegetal       NON  
3         0.0   2013  vegetal       NON  
4        82.0   2013  vegetal       NON

In [154]:
# Sélection des lignes de produits céréaliers

cereales_pour_animaux_nourriture_humaine = dm_cereales.loc[dm_cereales['is_cereal'] == 'OUI']
cereales_pour_animaux_nourriture_humaine

codePays          pays  codeProduit           produit  alim_ani  \
7             2   Afghanistan         2511               Blé       NaN   
12            2   Afghanistan         2520  Céréales, Autres       NaN   
32            2   Afghanistan         2514              Maïs     200.0   
34            2   Afghanistan         2517            Millet       NaN   
40            2   Afghanistan         2513              Orge     360.0   
...         ...           ...          ...               ...       ...   
15545        25  Îles Salomon         2520  Céréales, Autres       NaN   
15568        25  Îles Salomon         2514              Maïs       NaN   
15575        25  Îles Salomon         2513              Orge       NaN   
15591        25  Îles Salomon         2805  Riz (Eq Blanchi)       0.0   
15593        25  Îles Salomon         2518            Sorgho       0.0   

       nourriture  annee   origin is_cereal  
7          4895.0   2013  vegetal       OUI  
12            0.0   2013  vegetal       OUI  
32           76.0   2013  vegetal       OUI  
34           12.0   2013  vegetal       OUI  
40           89.0   2013  vegetal       OUI  
...           ...    ...      ...       ...  
15545         0.0   2013  vegetal       OUI  
15568         0.0   2013  vegetal       OUI  
15575         0.0   2013  vegetal       OUI  
15591        36.0   2013  vegetal       OUI  
15593         NaN   2013  vegetal       OUI  

[1497 rows x 9 columns]

In [155]:
liste_céréales = produit_cereales.drop_duplicates()
print('\nListe des produits (ainsi que leur code) considérés comme des céréales selon la FAO :\n')
liste_céréales


Liste des produits (ainsi que leur code) considérés comme des céréales selon la FAO :



Code Produit           Produit
0           2511               Blé
1           2805  Riz (Eq Blanchi)
2           2513              Orge
3           2514              Maïs
4           2517            Millet
9           2515            Seigle
10          2516            Avoine
12          2518            Sorgho
13          2520  Céréales, Autres

In [156]:
# Remplacement de Nan par '0' dans la table des produits céréaliers pour humains et pour animaux

conso_cereales = cereales_pour_animaux_nourriture_humaine.fillna(0)
conso_cereales

codePays          pays  codeProduit           produit  alim_ani  \
7             2   Afghanistan         2511               Blé       0.0   
12            2   Afghanistan         2520  Céréales, Autres       0.0   
32            2   Afghanistan         2514              Maïs     200.0   
34            2   Afghanistan         2517            Millet       0.0   
40            2   Afghanistan         2513              Orge     360.0   
...         ...           ...          ...               ...       ...   
15545        25  Îles Salomon         2520  Céréales, Autres       0.0   
15568        25  Îles Salomon         2514              Maïs       0.0   
15575        25  Îles Salomon         2513              Orge       0.0   
15591        25  Îles Salomon         2805  Riz (Eq Blanchi)       0.0   
15593        25  Îles Salomon         2518            Sorgho       0.0   

       nourriture  annee   origin is_cereal  
7          4895.0   2013  vegetal       OUI  
12            0.0   2013  vegetal       OUI  
32           76.0   2013  vegetal       OUI  
34           12.0   2013  vegetal       OUI  
40           89.0   2013  vegetal       OUI  
...           ...    ...      ...       ...  
15545         0.0   2013  vegetal       OUI  
15568         0.0   2013  vegetal       OUI  
15575         0.0   2013  vegetal       OUI  
15591        36.0   2013  vegetal       OUI  
15593         0.0   2013  vegetal       OUI  

[1497 rows x 9 columns]

In [157]:
# Sélection des données relatives aux céréales destinées à la consommation humaine 

conso_humaine_cereales = vegetaux.loc[(vegetaux['Élément'] == 'Nourriture')
                                      &
                                      (
                                        (vegetaux["Produit"] == 'Blé')
                                      | (vegetaux["Produit"] == 'Orge')
                                      | (vegetaux["Produit"] == 'Riz (Eq Blanchi)') 
                                      | (vegetaux["Produit"] == 'Maïs')
                                      | (vegetaux["Produit"] == 'Seigle')
                                      | (vegetaux["Produit"] == 'Avoine')
                                      | (vegetaux["Produit"] == 'Sorgho')
                                      | (vegetaux["Produit"] == 'Millet')
                                      | (vegetaux["Produit"] == 'Céréales, Autres')
                                      )
                                     ]
conso_humaine_cereales.head(2)

Code Domaine                                            Domaine  Code zone  \
6          FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
16         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

           Zone  Code Élément     Élément  Code Produit           Produit  \
6   Afghanistan          5142  Nourriture          2511               Blé   
16  Afghanistan          5142  Nourriture          2805  Riz (Eq Blanchi)   

    Code année  Année               Unité  Valeur Symbole  \
6         2013   2013  Milliers de tonnes  4895.0       S   
16        2013   2013  Milliers de tonnes   422.0       S   

   Description du Symbole   origin  
6   Données standardisées  vegetal  
16  Données standardisées  vegetal

In [158]:
total_conso_humaine_cereales = conso_humaine_cereales['Valeur'].sum()

print('\nCéréales destinées à la nourriture humaine : {} milliers de tonnes\n'.format(total_conso_humaine_cereales))


Céréales destinées à la nourriture humaine : 1029010.0 milliers de tonnes



In [159]:
# Sélection des données relatives aux céréales destinées à la consommation animale 

conso_animale_cereales = vegetaux.loc[(vegetaux['Élément'] == 'Aliments pour animaux')
                                      &
                                      (
                                        (vegetaux["Produit"] == 'Blé')
                                      | (vegetaux["Produit"] == 'Orge')
                                      | (vegetaux["Produit"] == 'Riz (Eq Blanchi)') 
                                      | (vegetaux["Produit"] == 'Maïs')
                                      | (vegetaux["Produit"] == 'Seigle')
                                      | (vegetaux["Produit"] == 'Avoine')
                                      | (vegetaux["Produit"] == 'Sorgho')
                                      | (vegetaux["Produit"] == 'Millet')
                                      | (vegetaux["Produit"] == 'Céréales, Autres')
                                      )
                                     ]
conso_animale_cereales.head(2)

Code Domaine                                            Domaine  Code zone  \
25         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   
37         FBSH  Bilans Alimentaire (Ancienne méthodologie et p...          2   

           Zone  Code Élément                Élément  Code Produit Produit  \
25  Afghanistan          5521  Aliments pour animaux          2513    Orge   
37  Afghanistan          5521  Aliments pour animaux          2514    Maïs   

    Code année  Année               Unité  Valeur Symbole  \
25        2013   2013  Milliers de tonnes   360.0       S   
37        2013   2013  Milliers de tonnes   200.0       S   

   Description du Symbole   origin  
25  Données standardisées  vegetal  
37  Données standardisées  vegetal

In [160]:
total_conso_animale_cereales = conso_animale_cereales['Valeur'].sum()

print('\nCéréales destinées à l\'alimentation animale : {} milliers de tonnes\n'.format(total_conso_animale_cereales))


Céréales destinées à l'alimentation animale : 873535.0 milliers de tonnes



In [161]:
# Consommation totale de céréales

total_conso_cereales = total_conso_animale_cereales + total_conso_humaine_cereales
print('\nConsommation totale de céréales : {} milliers de tonnes\n'.format(total_conso_cereales))


Consommation totale de céréales : 1902545.0 milliers de tonnes



**R11 - Proportion en terme de poids des céréales destinées à l'alimentation animale**

In [162]:
# Proportion de l'alimentation animale dans l'alimenation totale en céréales

prop_cereales_animale = round((total_conso_animale_cereales/total_conso_cereales)*100, 2)
print("\nProportion en terme de poids des céréales destinées à l\'alimentation animale {} %\n".format(prop_cereales_animale))


Proportion en terme de poids des céréales destinées à l'alimentation animale 45.91 %



**R11 : En ne prenant en compte que les céréales destinées à l'alimentation (humaine et animale), la proportion (en termes de poids) destinée à l'alimentation animale est de 46%**

** **

**Question 12 : Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)**
* le ratio entre la quantité destinés aux "Autres utilisations" et la disponibilité intérieure.
* le ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine)

In [163]:
# Sélection des informations relatives aux pays dans lesquels la FAO recense des personnes en sous_nutrition

sous_nutrition.rename(columns={'Code zone': 'codePays', 'Année': 'annee'}, inplace = True)

In [164]:
# Nous allons fusionner la table sous_alimentation avec celle ayant agrégé les données végétales et animales

data_merged_sous_alim = pd.concat([data_merged_cereales, sous_nutrition], axis = 1, join="inner")

# Nouvelle dénomination de colonnes

data_merged_sous_alim.rename(columns={'Valeur':'valeurProduit', 'Valeur réelle':'nb_sous_alim'}, inplace = True)

# Quantités exportées par pays 

qt_export_pays = data_merged_sous_alim.groupby('pays')['export'].sum()
df_qt_export_pays = pd.DataFrame(qt_export_pays)
print('\nQuantités exportées par pays:\n')
df_qt_export_pays


Quantités exportées par pays:



export
pays                       
Afghanistan            75.0
Afrique du Sud       2095.0
Albanie                11.0
Algérie                 1.0
Allemagne            4916.0
Angola                  0.0
Antigua-et-Barbuda      0.0
Arabie saoudite        59.0
Argentine            7237.0
Arménie                 4.0
Australie           28974.0
Autriche             1193.0

In [165]:
# Fusion de la table de sous-nutrition avec celle de base enrichie(animx+vegx+cereales)

data_merged_sous_alim_1 = pd.merge(data_merged_cereales, sous_nutrition, on=['codePays'])
data_merged_sous_alim_1.head(2)

pays  codePays  annee_x           produit  codeProduit   origin  \
0  Afghanistan         2     2013  Abats Comestible         2736   animal   
1  Afghanistan         2     2013   Agrumes, Autres         2614  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   

   Code Élément  Élément  Code Produit  \
0          6132   Valeur        210011   
1          6132   Valeur        210011   

                                             Produit  Code année    annee_y  \
0  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014   
1  Nombre de personnes sous-alimentées (millions)...    20122014  2012-2014   

   Symbole  Description du Symbole  Note  nb_personnes  
0        F          Estimation FAO   NaN     7900000.0  
1        F          Estimation FAO   NaN     7900000.0  

[2 rows x 35 columns]

In [166]:
# Nouvelle dénomination de colonnes

data_merged_sous_alim_1.drop(['annee_y'], axis = 1, inplace = True)
data_merged_sous_alim_1.rename(columns={'annee_x':'annee','Valeur':'valeurProduit', 'Valeur réelle':'nb_sous_alim'}, inplace = True)
data_merged_sous_alim_1.head(2)

pays  codePays  annee           produit  codeProduit   origin  \
0  Afghanistan         2   2013  Abats Comestible         2736   animal   
1  Afghanistan         2   2013   Agrumes, Autres         2614  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   

          Zone  Code Élément  Élément  Code Produit  \
0  Afghanistan          6132   Valeur        210011   
1  Afghanistan          6132   Valeur        210011   

                                             Produit  Code année  Symbole  \
0  Nombre de personnes sous-alimentées (millions)...    20122014        F   
1  Nombre de personnes sous-alimentées (millions)...    20122014        F   

   Description du Symbole  Note  nb_personnes  
0          Estimation FAO   NaN     7900000.0  
1          Estimation FAO   NaN     7900000.0  

[2 rows x 34 columns]

In [167]:
# Produits les plus exportés par les pays en sous-nutrition

produits_plus_export = data_merged_sous_alim_1[['codePays','pays','produit','export']].sort_values(by = 'export', ascending = False) 

# data_merged_sous_alim_1[['pays','produit','export_quantite']].sort_values(by = 'export_quantite', ascending = False) 

print('\nTable contenant les produits les plus exportés:\n')

produits_plus_export_pertinents = produits_plus_export # = produits_plus_export.head(60)
produits_plus_export


Table contenant les produits les plus exportés:



codePays          pays                 produit   export
9112        216     Thaïlande                  Manioc  25214.0
4192        101     Indonésie          Huile de Palme  23333.0
564           9     Argentine                    Maïs  20241.0
5308        131      Malaisie          Huile de Palme  19622.0
4135        100          Inde        Riz (Eq Blanchi)  11337.0
...         ...           ...                     ...      ...
10529        25  Îles Salomon  Viande d'Ovins/Caprins      NaN
10530        25  Îles Salomon        Viande de Bovins      NaN
10531        25  Îles Salomon        Viande de Suides      NaN
10532        25  Îles Salomon     Viande de Volailles      NaN
10533        25  Îles Salomon           Viande, Autre      NaN

[10536 rows x 4 columns]

In [168]:
# Correction de la table

produits_plus_export['export'] = produits_plus_export['export'].replace(0.0, np.nan)
produits_plus_export_dropna = produits_plus_export.dropna()
produits_plus_export_dropna

codePays       pays                  produit   export
9112       216  Thaïlande                   Manioc  25214.0
4192       101  Indonésie           Huile de Palme  23333.0
564          9  Argentine                     Maïs  20241.0
5308       131   Malaisie           Huile de Palme  19622.0
4135       100       Inde         Riz (Eq Blanchi)  11337.0
...        ...        ...                      ...      ...
8440       272     Serbie         Riz (Eq Blanchi)      1.0
8650       276     Soudan                   Dattes      1.0
9400       222    Tunisie          Agrumes, Autres      1.0
3111        66      Fidji            Huile de Coco      1.0
3237        74      Gabon  Poissons Marins, Autres      1.0

[3082 rows x 4 columns]

In [169]:
export_produit_pays = produits_plus_export_dropna.groupby(['produit']).sum()

export_produit_pays_tri = export_produit_pays.sort_values(by = ['export'], ascending = False)

# Sélection des attributs pertinents

produits_plus_exportés = export_produit_pays_tri['export']
df_produits_plus_exportés = pd.DataFrame(produits_plus_exportés)
quinze_produits_plus_export = df_produits_plus_exportés.head(15)
print('\nListe des 15 produits les plus exportés par les pays en sous-nutrition :\n')

quinze_produits_plus_export


Liste des 15 produits les plus exportés par les pays en sous-nutrition :



export
produit                     
Huile de Palme       46324.0
Maïs                 37906.0
Manioc               35851.0
Riz (Eq Blanchi)     33093.0
Sucre Eq Brut        26098.0
Blé                  25342.0
Légumes, Autres      20139.0
Bananes              17988.0
Lait - Excl Beurre   14973.0
Fruits, Autres       14690.0
Soja                 14391.0
Poissons Pelagiques  14181.0
Tomates               8935.0
Pommes                7897.0
Oranges, Mandarines   7106.0

**Parmi les données des bilans alimentaires au niveau mondial, sélectionnez les 200 plus grandes importations de ces produits (1 importation = une quantité d'un produit donné importée par un pays donné)**

In [170]:
produits_plus_import = data_merged_sous_alim_1[['pays','Code Produit','produit','import']].sort_values(by = 'import', ascending = False) 
# data_merged_sous_alim_1[['pays','produit','export_quantite']].sort_values(by = 'export_quantite', ascending = False) 

print('\nTable contenant des produits les plus importés:\n')

#produits_plus_import_pertinents = produits_plus_import # = produits_plus_export.head(60)

produits_plus_import_dropna = produits_plus_import.dropna()
produits_plus_import_dropna


Table contenant des produits les plus importés:



pays  Code Produit             produit   import
2150   Chine, continentale        210011                Soja  63381.0
2120   Chine, continentale        210011              Manioc  29046.0
480        Arabie saoudite        210011                Orge  10547.0
10097               Égypte        210011                 Blé  10331.0
4095                  Inde        210011      Huile de Palme   8568.0
...                    ...           ...                 ...      ...
2856           El Salvador        210011              Olives      0.0
1620              Cambodge        210011  Boissons Fermentés      0.0
2852           El Salvador        210011  Mollusques, Autres      0.0
7104              Pakistan        210011               Crème      0.0
10535         Îles Salomon        210011      Épices, Autres      0.0

[9918 rows x 4 columns]

In [171]:
import_produit_pays = produits_plus_import_dropna.groupby(['produit']).sum()

import_produit_pays_tri = import_produit_pays.sort_values(by = ['import'], ascending = False)

# Sélection des attributs pertinents

produits_plus_importés = import_produit_pays_tri['import']
df_produits_plus_importés = pd.DataFrame(produits_plus_importés)
deux_cent_produits_plus_import = df_produits_plus_importés.head(200)
print('\nListe des 200 produits les plus importés par les pays en sous-nutrition:\n')

deux_cent_produits_plus_import


Liste des 200 produits les plus importés par les pays en sous-nutrition:



import
produit                           
Blé                       104658.0
Soja                       78186.0
Maïs                       61836.0
Lait - Excl Beurre         43467.0
Sucre Eq Brut              39288.0
...                            ...
Animaux Aquatiques Autre      19.0
Huile de Sésame               15.0
Huiles de Foie de Poisso       4.0
Ignames                        2.0
Huile de Son de Riz            1.0

[96 rows x 1 columns]

In [172]:
# Sélection des attributs approppriés de la table de sous-nutrition

extract_sous_alimentation = sous_nutrition[['codePays','Zone','nb_personnes']]

# Colonne renommée
extract_sous_alimentation.rename(columns={'nb_personnes':'nb_hbts_sous_alim'}, inplace = True)
extract_sous_alimentation

codePays                                    Zone  nb_hbts_sous_alim
0            2                             Afghanistan          7900000.0
5          202                          Afrique du Sud          2600000.0
10           3                                 Albanie           200000.0
15           4                                 Algérie          1700000.0
30           7                                  Angola          8100000.0
...        ...                                     ...                ...
995        236  Venezuela (République bolivarienne du)          1900000.0
1000       237                                Viet Nam         10400000.0
1005       249                                   Yémen          7200000.0
1010       251                                  Zambie          7000000.0
1015       181                                Zimbabwe          6600000.0

[120 rows x 3 columns]

In [173]:
# Fusion entre table de sous-alimentation et celle des exportations (export_produit_pays_tri)

exportation_sous_aliment = pd.merge(extract_sous_alimentation, produits_plus_export, on = ['codePays'], how = 'left')

# Remplacement de '0' par Nan

exportation_sous_aliment['export'] = exportation_sous_aliment['export'].replace(0.0, np.nan)

# Suppression des Nan

exportation_sous_aliment_dropna = exportation_sous_aliment.dropna()

# Tri décroissant de la table

tri_exportation_sous_aliment_dropna =  exportation_sous_aliment_dropna.sort_values(by =['export'], ascending = False)
tri_exportation_sous_aliment_dropna

codePays       Zone  nb_hbts_sous_alim       pays              produit  \
9514        216  Thaïlande          5600000.0  Thaïlande               Manioc   
4605        101  Indonésie         22600000.0  Indonésie       Huile de Palme   
514           9  Argentine          1500000.0  Argentine                 Maïs   
5721        131   Malaisie          1000000.0   Malaisie       Huile de Palme   
4508        100       Inde        216300000.0       Inde     Riz (Eq Blanchi)   
...         ...        ...                ...        ...                  ...   
1163         20   Botswana           500000.0   Botswana  Poissons Pelagiques   
1162         20   Botswana           500000.0   Botswana               Sorgho   
1161         20   Botswana           500000.0   Botswana   Lait - Excl Beurre   
6191        137    Maurice            50000.0    Maurice        Huile de Soja   
10463       181   Zimbabwe          6600000.0   Zimbabwe     Riz (Eq Blanchi)   

        export  
9514   25214.0  
4605   23333.0  
514    20241.0  
5721   19622.0  
4508   11337.0  
...        ...  
1163       1.0  
1162       1.0  
1161       1.0  
6191       1.0  
10463      1.0  

[3082 rows x 6 columns]

In [174]:
# Sélection des lignes de nombre d'habitants non nul

sous_alim_tri_exportation_sous_aliment_dropna = tri_exportation_sous_aliment_dropna.loc[tri_exportation_sous_aliment_dropna['nb_hbts_sous_alim'] != 0]

# Suppression de la colonne 'Zone'

t = sous_alim_tri_exportation_sous_aliment_dropna.drop('Zone', axis = 1)

s = t.groupby('produit').sum()
q = s['export']
produits_plus_export_par_pays_sous_alim = pd.DataFrame(q)

# Tri des produits les plus exportés

tri_produits_plus_export_par_pays_sous_alim = produits_plus_export_par_pays_sous_alim.sort_values(by=['export'], ascending =False)

quinze_plus_exportes_par_sous_alim = tri_produits_plus_export_par_pays_sous_alim.head(15)

print('\nListe des 15 produits les plus exportés par les pays en sous-alimentation\n')
# d.size
quinze_plus_exportes_par_sous_alim


Liste des 15 produits les plus exportés par les pays en sous-alimentation



export
produit                     
Huile de Palme       46324.0
Maïs                 37906.0
Manioc               35851.0
Riz (Eq Blanchi)     33093.0
Sucre Eq Brut        26098.0
Blé                  25342.0
Légumes, Autres      20139.0
Bananes              17988.0
Lait - Excl Beurre   14973.0
Fruits, Autres       14690.0
Soja                 14391.0
Poissons Pelagiques  14181.0
Tomates               8935.0
Pommes                7897.0
Oranges, Mandarines   7106.0

In [175]:
# Extraction des colonnes approppriées

qte_import = data_merged[['pays','produit','import']]
qte_import.head(2)

pays           produit  import
0  Afghanistan  Abats Comestible     NaN
1  Afghanistan   Agrumes, Autres    40.0

In [176]:
# Nous allons joindre la table des 15 produits les plus exportés(df_quinze_produits_plus_exportés) avec celle des importations(qte_import)
# Ensuite, nous sélectionnerons les 200 produits les plus importés

In [177]:
# Construction de la colonne "is_cereale"

def set_import(row):
    if    (row["produit"] == 'Soja'
        or row["produit"] == 'Blé'
        or row["produit"] == 'Orge'
        or row["produit"] == 'Sucre Eq Brut'
        or row["produit"] == 'Manioc'
        or row["produit"] == 'Huile de Palme'
        or row["produit"] == 'Lait - Excl Beurre'
        or row["produit"] == 'Oranges, Mandarines'
        or row["produit"] == 'Légumes, Autres'
        or row["produit"] == 'Graines Colza/Moutarde'
        or row["produit"] == 'Pommes de Terre'
        or row["produit"] == 'Bananes'
        or row["produit"] == 'Poissons Pelagiques'  
        or row["produit"] == 'Riz (Eq Blanchi)'
        or row["produit"] == 'Maïs'):
        return "OUI"
    else:
        return "NON"
    
import_p = qte_import.assign(importe=qte_import.apply(set_import, axis=1))

print('\nLa table des produits les sujets à l\'import-export:\n')
import_p


La table des produits les sujets à l'import-export:



pays                produit  import importe
0       Afghanistan       Abats Comestible     NaN     NON
1       Afghanistan        Agrumes, Autres    40.0     NON
2       Afghanistan  Aliments pour enfants     2.0     NON
3       Afghanistan                 Ananas     0.0     NON
4       Afghanistan                Bananes    82.0     OUI
...             ...                    ...     ...     ...
15600  Îles Salomon       Viande de Suides     0.0     NON
15601  Îles Salomon    Viande de Volailles     2.0     NON
15602  Îles Salomon          Viande, Autre     0.0     NON
15603  Îles Salomon                    Vin     0.0     NON
15604  Îles Salomon         Épices, Autres     0.0     NON

[15605 rows x 4 columns]

In [178]:
# Sélection des produits importés

import_oui = import_p.loc[import_p['importe'] == 'OUI']
print('\nLes produits les plus importés:\n')
import_oui


Les produits les plus importés:



pays              produit  import importe
4       Afghanistan              Bananes    82.0     OUI
7       Afghanistan                  Blé  1173.0     OUI
25      Afghanistan       Huile de Palme   119.0     OUI
29      Afghanistan   Lait - Excl Beurre   248.0     OUI
30      Afghanistan      Légumes, Autres   124.0     OUI
...             ...                  ...     ...     ...
15585  Îles Salomon  Poissons Pelagiques     0.0     OUI
15588  Îles Salomon      Pommes de Terre     0.0     OUI
15591  Îles Salomon     Riz (Eq Blanchi)    47.0     OUI
15592  Îles Salomon                 Soja     0.0     OUI
15594  Îles Salomon        Sucre Eq Brut     2.0     OUI

[2570 rows x 4 columns]

In [179]:
# Remplacement de '0' par Nan

import_oui['import'] = import_oui['import'].replace(0.0, np.nan)

# Suppression des Nan

import_oui_dropna = import_oui.dropna()
import_oui_dropna

pays              produit  import importe
4       Afghanistan              Bananes    82.0     OUI
7       Afghanistan                  Blé  1173.0     OUI
25      Afghanistan       Huile de Palme   119.0     OUI
29      Afghanistan   Lait - Excl Beurre   248.0     OUI
30      Afghanistan      Légumes, Autres   124.0     OUI
...             ...                  ...     ...     ...
15564  Îles Salomon   Lait - Excl Beurre     5.0     OUI
15574  Îles Salomon  Oranges, Mandarines     1.0     OUI
15575  Îles Salomon                 Orge     1.0     OUI
15591  Îles Salomon     Riz (Eq Blanchi)    47.0     OUI
15594  Îles Salomon        Sucre Eq Brut     2.0     OUI

[2175 rows x 4 columns]

In [180]:
# Tri des données en fonction de la quantité importée

import_oui_dropna_tri = import_oui_dropna.sort_values(by=['import'], ascending=False)
import_oui_dropna_tri

pays              produit   import importe
3353   Chine, continentale                 Soja  63381.0     OUI
3323   Chine, continentale               Manioc  29046.0     OUI
7074                 Japon                 Maïs  14403.0     OUI
666        Arabie saoudite                 Orge  10547.0     OUI
15071               Égypte                  Blé  10331.0     OUI
...                    ...                  ...      ...     ...
1630              Bermudes              Bananes      1.0     OUI
1603                Belize  Poissons Pelagiques      1.0     OUI
6607               Irlande               Manioc      1.0     OUI
1583                Belize                 Maïs      1.0     OUI
5356               Grenade                 Orge      1.0     OUI

[2175 rows x 4 columns]

In [181]:
# Sélection des 200 produits les plus importés

import_200_plus_importe = import_oui_dropna_tri.head(200)
print('\nLes 200 produits les plus importés:\n')
import_200_plus_importe


Les 200 produits les plus importés:



pays           produit   import importe
3353   Chine, continentale              Soja  63381.0     OUI
3323   Chine, continentale            Manioc  29046.0     OUI
7074                 Japon              Maïs  14403.0     OUI
666        Arabie saoudite              Orge  10547.0     OUI
15071               Égypte               Blé  10331.0     OUI
...                    ...               ...      ...     ...
13510              Sénégal  Riz (Eq Blanchi)   1120.0     OUI
11799  République de Corée              Soja   1118.0     OUI
11767  République de Corée   Légumes, Autres   1105.0     OUI
6334             Indonésie            Manioc   1102.0     OUI
7316                 Kenya               Blé   1092.0     OUI

[200 rows x 4 columns]

In [182]:
qtit_import_par_produit = import_oui_dropna_tri.groupby('produit').sum()
qtit_import_par_produit

import
produit                         
Bananes                  19424.0
Blé                     185377.0
Graines Colza/Moutarde   21052.0
Huile de Palme           48858.0
Lait - Excl Beurre      116806.0
Légumes, Autres          43333.0
Manioc                   38370.0
Maïs                    122691.0
Oranges, Mandarines      35011.0
Orge                     38689.0
Poissons Pelagiques      28598.0
Pommes de Terre          31599.0
Riz (Eq Blanchi)         37618.0
Soja                    102082.0
Sucre Eq Brut            61615.0

In [183]:
# Jointure de la table 'mère' data_merged avec  celle des produits importés par les pays en sous-alimentation

merge_import = data_merged.merge( qtit_import_par_produit, on=['produit'], how = 'left')
merge_import.head(2)

pays  codePays  annee           produit  codeProduit   origin  \
0  Afghanistan         2   2013  Abats Comestible         2736   animal   
1  Afghanistan         2   2013   Agrumes, Autres         2614  vegetal   

   alim_ani  autres_utilisations  dispo_alim_kcal_p_j  dispo_alim_kg_p  ...  \
0       NaN                  NaN                  5.0             1.72  ...   
1       NaN                  NaN                  1.0             1.29  ...   

   export  import_x  nourriture  pertes  production  semences  transfo  \
0     NaN       NaN        53.0     NaN        53.0       NaN      NaN   
1     2.0      40.0        39.0     2.0         3.0       NaN      NaN   

   var_stock  nb_habitants  import_y  
0        NaN      30552000       NaN  
1        NaN      30552000       NaN  

[2 rows x 23 columns]

In [184]:
# Rappel des attributs de la table de base

list(merge_import)

['pays',
 'codePays',
 'annee',
 'produit',
 'codeProduit',
 'origin',
 'alim_ani',
 'autres_utilisations',
 'dispo_alim_kcal_p_j',
 'dispo_alim_kg_p',
 'dispo_mat_gr_g_p_j',
 'dispo_prot_g_p_j',
 'dispo_int',
 'export',
 'import_x',
 'nourriture',
 'pertes',
 'production',
 'semences',
 'transfo',
 'var_stock',
 'nb_habitants',
 'import_y']

In [185]:
# Corrections de la table

merge_import_qt = merge_import.rename(columns={'import_y':'quantité_imports'})
merge_import_qt_drop = merge_import_qt.drop('import_x', axis=1)

# sélection des colonnes pertinentes

#data_merged_selec_aut_util_disp_int = merge_import[['pays','produit','autres_utilisations','disponibilite_interieure','import_quantite_y']]
data_merged_selec_aut_util_disp_int = merge_import_qt_drop[['pays','produit','autres_utilisations','dispo_int','quantité_imports']]

# Remplacement de '0' par Nan

data_merged_selec_aut_util_disp_int['quantité_imports'] = data_merged_selec_aut_util_disp_int['quantité_imports'].replace(0.0, np.nan)
data_merged_selec_aut_util_disp_int['autres_utilisations'] = data_merged_selec_aut_util_disp_int['autres_utilisations'].replace(0.0, np.nan)
data_merged_selec_aut_util_disp_int['dispo_int'] = data_merged_selec_aut_util_disp_int['dispo_int'].replace(0.0, np.nan)

# Suppression des Nan

data_merged_selec_aut_util_disp_int_dropna = data_merged_selec_aut_util_disp_int.dropna()
data_merged_selec_aut_util_disp_int_dropna

pays           produit  autres_utilisations  \
25               Afghanistan    Huile de Palme                 55.0   
99            Afrique du Sud    Huile de Palme                399.0   
110           Afrique du Sud            Manioc                 57.0   
135           Afrique du Sud   Pommes de Terre                103.0   
167                  Albanie               Blé                130.0   
...                      ...               ...                  ...   
15422  États-Unis d'Amérique     Sucre Eq Brut                107.0   
15445               Éthiopie               Blé               1600.0   
15472               Éthiopie    Huile de Palme                 18.0   
15556           Îles Salomon    Huile de Palme                  1.0   
15591           Îles Salomon  Riz (Eq Blanchi)                 12.0   

       dispo_int  quantité_imports  
25         119.0           48858.0  
99         449.0           48858.0  
110         57.0           38370.0  
135       2126.0           31599.0  
167        650.0          185377.0  
...          ...               ...  
15422    10353.0           61615.0  
15445     4906.0          185377.0  
15472      223.0           48858.0  
15556        2.0           48858.0  
15591       49.0           37618.0  

[821 rows x 5 columns]

In [186]:
# Calcul du ratio autres 'utilisations/disponibilités intérieures'

data_merged_selec_aut_util_disp_int_dropna['ratio_autres_utilisations_disponibilite_interieure'] = data_merged_selec_aut_util_disp_int_dropna['autres_utilisations']/data_merged_selec_aut_util_disp_int_dropna['quantité_imports']
data_merged_selec_aut_util_disp_int_dropna

pays           produit  autres_utilisations  \
25               Afghanistan    Huile de Palme                 55.0   
99            Afrique du Sud    Huile de Palme                399.0   
110           Afrique du Sud            Manioc                 57.0   
135           Afrique du Sud   Pommes de Terre                103.0   
167                  Albanie               Blé                130.0   
...                      ...               ...                  ...   
15422  États-Unis d'Amérique     Sucre Eq Brut                107.0   
15445               Éthiopie               Blé               1600.0   
15472               Éthiopie    Huile de Palme                 18.0   
15556           Îles Salomon    Huile de Palme                  1.0   
15591           Îles Salomon  Riz (Eq Blanchi)                 12.0   

       dispo_int  quantité_imports  \
25         119.0           48858.0   
99         449.0           48858.0   
110         57.0           38370.0   
135       2126.0           31599.0   
167        650.0          185377.0   
...          ...               ...   
15422    10353.0           61615.0   
15445     4906.0          185377.0   
15472      223.0           48858.0   
15556        2.0           48858.0   
15591       49.0           37618.0   

       ratio_autres_utilisations_disponibilite_interieure  
25                                              0.001126   
99                                              0.008167   
110                                             0.001486   
135                                             0.003260   
167                                             0.000701   
...                                                  ...   
15422                                           0.001737   
15445                                           0.008631   
15472                                           0.000368   
15556                                           0.000020   
15591                                           0.000319   

[821 rows x 6 columns]

In [187]:
# Sélection des colonnes utiles

nourriture_animale_nourriture_humaine = data_merged[['pays','produit','alim_ani','nourriture']]
nourriture_animale_nourriture_humaine

pays                produit  alim_ani  nourriture
0       Afghanistan       Abats Comestible       NaN        53.0
1       Afghanistan        Agrumes, Autres       NaN        39.0
2       Afghanistan  Aliments pour enfants       NaN         2.0
3       Afghanistan                 Ananas       NaN         0.0
4       Afghanistan                Bananes       NaN        82.0
...             ...                    ...       ...         ...
15600  Îles Salomon       Viande de Suides       NaN         3.0
15601  Îles Salomon    Viande de Volailles       NaN         2.0
15602  Îles Salomon          Viande, Autre       NaN         0.0
15603  Îles Salomon                    Vin       NaN         0.0
15604  Îles Salomon         Épices, Autres       NaN         0.0

[15605 rows x 4 columns]

In [188]:
# Calcul de la nourriture totale et ajout de la colonne à la table

nourriture_animale_nourriture_humaine['nourriture_totale'] = nourriture_animale_nourriture_humaine['alim_ani']+nourriture_animale_nourriture_humaine['nourriture']
nourriture_animale_nourriture_humaine

pays                produit  alim_ani  nourriture  \
0       Afghanistan       Abats Comestible       NaN        53.0   
1       Afghanistan        Agrumes, Autres       NaN        39.0   
2       Afghanistan  Aliments pour enfants       NaN         2.0   
3       Afghanistan                 Ananas       NaN         0.0   
4       Afghanistan                Bananes       NaN        82.0   
...             ...                    ...       ...         ...   
15600  Îles Salomon       Viande de Suides       NaN         3.0   
15601  Îles Salomon    Viande de Volailles       NaN         2.0   
15602  Îles Salomon          Viande, Autre       NaN         0.0   
15603  Îles Salomon                    Vin       NaN         0.0   
15604  Îles Salomon         Épices, Autres       NaN         0.0   

       nourriture_totale  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
...                  ...  
15600                NaN  
15601                NaN  
15602                NaN  
15603                NaN  
15604                NaN  

[15605 rows x 5 columns]

In [189]:
# Fusion des tables de nourriture et d'importation

merge_nourritures_import = nourriture_animale_nourriture_humaine.merge(qtit_import_par_produit, on=['produit'], how = 'left')
merge_nourritures_import

pays                produit  alim_ani  nourriture  \
0       Afghanistan       Abats Comestible       NaN        53.0   
1       Afghanistan        Agrumes, Autres       NaN        39.0   
2       Afghanistan  Aliments pour enfants       NaN         2.0   
3       Afghanistan                 Ananas       NaN         0.0   
4       Afghanistan                Bananes       NaN        82.0   
...             ...                    ...       ...         ...   
15600  Îles Salomon       Viande de Suides       NaN         3.0   
15601  Îles Salomon    Viande de Volailles       NaN         2.0   
15602  Îles Salomon          Viande, Autre       NaN         0.0   
15603  Îles Salomon                    Vin       NaN         0.0   
15604  Îles Salomon         Épices, Autres       NaN         0.0   

       nourriture_totale   import  
0                    NaN      NaN  
1                    NaN      NaN  
2                    NaN      NaN  
3                    NaN      NaN  
4                    NaN  19424.0  
...                  ...      ...  
15600                NaN      NaN  
15601                NaN      NaN  
15602                NaN      NaN  
15603                NaN      NaN  
15604                NaN      NaN  

[15605 rows x 6 columns]

In [190]:
# Suppression de la colonne non nécessaire

merge_nourritures_import.drop('import', axis=1, inplace=True)
merge_nourritures_import

pays                produit  alim_ani  nourriture  \
0       Afghanistan       Abats Comestible       NaN        53.0   
1       Afghanistan        Agrumes, Autres       NaN        39.0   
2       Afghanistan  Aliments pour enfants       NaN         2.0   
3       Afghanistan                 Ananas       NaN         0.0   
4       Afghanistan                Bananes       NaN        82.0   
...             ...                    ...       ...         ...   
15600  Îles Salomon       Viande de Suides       NaN         3.0   
15601  Îles Salomon    Viande de Volailles       NaN         2.0   
15602  Îles Salomon          Viande, Autre       NaN         0.0   
15603  Îles Salomon                    Vin       NaN         0.0   
15604  Îles Salomon         Épices, Autres       NaN         0.0   

       nourriture_totale  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
...                  ...  
15600                NaN  
15601                NaN  
15602                NaN  
15603                NaN  
15604                NaN  

[15605 rows x 5 columns]

In [191]:
merge_nourritures_import['alim_ani'] = merge_nourritures_import['alim_ani'].replace(0.0, np.nan)
merge_nourritures_import['nourriture'] = merge_nourritures_import['nourriture'].replace(0.0, np.nan)
merge_nourritures_import['nourriture_totale'] = merge_nourritures_import['nourriture_totale'].replace(0.0, np.nan)

# Suppression des Nan

merge_nourritures_import_dropna = merge_nourritures_import.dropna()
merge_nourritures_import_dropna

pays                 produit  alim_ani  nourriture  \
29               Afghanistan      Lait - Excl Beurre     123.0      1901.0   
31               Afghanistan     Légumineuses Autres       4.0        74.0   
32               Afghanistan                    Maïs     200.0        76.0   
40               Afghanistan                    Orge     360.0        89.0   
67            Afrique du Sud                  Avoine       8.0        40.0   
...                      ...                     ...       ...         ...   
15421  États-Unis d'Amérique                  Sorgho    2351.0       236.0   
15428  États-Unis d'Amérique  Viande d'Ovins/Caprins      16.0       139.0   
15432  États-Unis d'Amérique           Viande, Autre      33.0       259.0   
15480               Éthiopie      Lait - Excl Beurre      18.0      4153.0   
15483               Éthiopie                    Maïs     667.0      3960.0   

       nourriture_totale  
29                2024.0  
31                  78.0  
32                 276.0  
40                 449.0  
67                  48.0  
...                  ...  
15421             2587.0  
15428              155.0  
15432              292.0  
15480             4171.0  
15483             4627.0  

[1380 rows x 5 columns]

In [192]:
# Calcul du ratio et ajout de la colonne à la table

merge_nourritures_import_dropna['ratio_nourritures'] = merge_nourritures_import_dropna['alim_ani']/merge_nourritures_import_dropna['nourriture_totale']
print('\nTable du ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine):\n')
merge_nourritures_import_dropna


Table du ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine):



pays                 produit  alim_ani  nourriture  \
29               Afghanistan      Lait - Excl Beurre     123.0      1901.0   
31               Afghanistan     Légumineuses Autres       4.0        74.0   
32               Afghanistan                    Maïs     200.0        76.0   
40               Afghanistan                    Orge     360.0        89.0   
67            Afrique du Sud                  Avoine       8.0        40.0   
...                      ...                     ...       ...         ...   
15421  États-Unis d'Amérique                  Sorgho    2351.0       236.0   
15428  États-Unis d'Amérique  Viande d'Ovins/Caprins      16.0       139.0   
15432  États-Unis d'Amérique           Viande, Autre      33.0       259.0   
15480               Éthiopie      Lait - Excl Beurre      18.0      4153.0   
15483               Éthiopie                    Maïs     667.0      3960.0   

       nourriture_totale  ratio_nourritures  
29                2024.0           0.060771  
31                  78.0           0.051282  
32                 276.0           0.724638  
40                 449.0           0.801782  
67                  48.0           0.166667  
...                  ...                ...  
15421             2587.0           0.908775  
15428              155.0           0.103226  
15432              292.0           0.113014  
15480             4171.0           0.004316  
15483             4627.0           0.144154  

[1380 rows x 6 columns]

**Question 12 : Donnez les 3 produits qui ont la plus grande valeur pour chacun des 2 ratios (vous aurez donc 6 produits à citer)**

In [193]:
# Rappel de la table ratio autres utilisationss/disponibilité intérieure

data_merged_selec_aut_util_disp_int_dropna

pays           produit  autres_utilisations  \
25               Afghanistan    Huile de Palme                 55.0   
99            Afrique du Sud    Huile de Palme                399.0   
110           Afrique du Sud            Manioc                 57.0   
135           Afrique du Sud   Pommes de Terre                103.0   
167                  Albanie               Blé                130.0   
...                      ...               ...                  ...   
15422  États-Unis d'Amérique     Sucre Eq Brut                107.0   
15445               Éthiopie               Blé               1600.0   
15472               Éthiopie    Huile de Palme                 18.0   
15556           Îles Salomon    Huile de Palme                  1.0   
15591           Îles Salomon  Riz (Eq Blanchi)                 12.0   

       dispo_int  quantité_imports  \
25         119.0           48858.0   
99         449.0           48858.0   
110         57.0           38370.0   
135       2126.0           31599.0   
167        650.0          185377.0   
...          ...               ...   
15422    10353.0           61615.0   
15445     4906.0          185377.0   
15472      223.0           48858.0   
15556        2.0           48858.0   
15591       49.0           37618.0   

       ratio_autres_utilisations_disponibilite_interieure  
25                                              0.001126   
99                                              0.008167   
110                                             0.001486   
135                                             0.003260   
167                                             0.000701   
...                                                  ...   
15422                                           0.001737   
15445                                           0.008631   
15472                                           0.000368   
15556                                           0.000020   
15591                                           0.000319   

[821 rows x 6 columns]

In [194]:
# Sélection des variables pertinentes

autres_util_dispo_int = data_merged_selec_aut_util_disp_int_dropna[['produit','autres_utilisations','dispo_int']]

# Regroupement par produit

autres_util_dispo_int_par_produit = autres_util_dispo_int.groupby('produit').sum()
autres_util_dispo_int_par_produit


autres_utilisations  dispo_int
produit                                               
Bananes                               142.0     2147.0
Blé                                 22424.0   502747.0
Graines Colza/Moutarde                314.0    23518.0
Huile de Palme                      35191.0    50060.0
Lait - Excl Beurre                  18768.0   444404.0
Légumes, Autres                       490.0    13058.0
Manioc                              35987.0   153025.0
Maïs                               189386.0   822334.0
Oranges, Mandarines                   115.0     9281.0
Orge                                  654.0    46453.0
Poissons Pelagiques                   376.0     2540.0
Pommes de Terre                     10660.0   339454.0
Riz (Eq Blanchi)                    18464.0   329490.0
Soja                                  638.0     6274.0
Sucre Eq Brut                       13130.0    70424.0

In [195]:
# Calcul du ratio autres_utilisations/dispo_int

autres_util_dispo_int_par_produit['ratio_autres_utilisations_disponibilite_interieure'] = autres_util_dispo_int_par_produit['autres_utilisations'] / autres_util_dispo_int_par_produit['dispo_int']

# Classement du ratio autres utilisations/disponibilite_interieure par ordre décroissant

print('\nTable des ratios "autres_utilisations/dispo_int" classée par ordre décroissant:\n')
autres_util_dispo_int_par_produit.sort_values(by=['ratio_autres_utilisations_disponibilite_interieure'], ascending=False)



Table des ratios "autres_utilisations/dispo_int" classée par ordre décroissant:



autres_utilisations  dispo_int  \
produit                                                  
Huile de Palme                      35191.0    50060.0   
Manioc                              35987.0   153025.0   
Maïs                               189386.0   822334.0   
Sucre Eq Brut                       13130.0    70424.0   
Poissons Pelagiques                   376.0     2540.0   
Soja                                  638.0     6274.0   
Bananes                               142.0     2147.0   
Riz (Eq Blanchi)                    18464.0   329490.0   
Blé                                 22424.0   502747.0   
Lait - Excl Beurre                  18768.0   444404.0   
Légumes, Autres                       490.0    13058.0   
Pommes de Terre                     10660.0   339454.0   
Orge                                  654.0    46453.0   
Graines Colza/Moutarde                314.0    23518.0   
Oranges, Mandarines                   115.0     9281.0   

                        ratio_autres_utilisations_disponibilite_interieure  
produit                                                                     
Huile de Palme                                                   0.702976   
Manioc                                                           0.235171   
Maïs                                                             0.230303   
Sucre Eq Brut                                                    0.186442   
Poissons Pelagiques                                              0.148031   
Soja                                                             0.101690   
Bananes                                                          0.066139   
Riz (Eq Blanchi)                                                 0.056038   
Blé                                                              0.044603   
Lait - Excl Beurre                                               0.042232   
Légumes, Autres                                                  0.037525   
Pommes de Terre                                                  0.031403   
Orge                                                             0.014079   
Graines Colza/Moutarde                                           0.013351   
Oranges, Mandarines                                              0.012391

In [196]:
autres_util_dispo_int_par_produit.head(10)

autres_utilisations  dispo_int  \
produit                                                  
Bananes                               142.0     2147.0   
Blé                                 22424.0   502747.0   
Graines Colza/Moutarde                314.0    23518.0   
Huile de Palme                      35191.0    50060.0   
Lait - Excl Beurre                  18768.0   444404.0   
Légumes, Autres                       490.0    13058.0   
Manioc                              35987.0   153025.0   
Maïs                               189386.0   822334.0   
Oranges, Mandarines                   115.0     9281.0   
Orge                                  654.0    46453.0   

                        ratio_autres_utilisations_disponibilite_interieure  
produit                                                                     
Bananes                                                          0.066139   
Blé                                                              0.044603   
Graines Colza/Moutarde                                           0.013351   
Huile de Palme                                                   0.702976   
Lait - Excl Beurre                                               0.042232   
Légumes, Autres                                                  0.037525   
Manioc                                                           0.235171   
Maïs                                                             0.230303   
Oranges, Mandarines                                              0.012391   
Orge                                                             0.014079

**Trois produits du plus grand ratio 'nourriture animale/nourriture totale' :**
* 1 - Avoine
* 2 - Manioc
* 3 - Orge


**R12.1 : Ratio entre les autres_utilisations et disponibilite_interieure :** 
* 1 - Bananes
* 2 - Blé
* 3 - Graines Colza/Moutarde

**R12.2 : Ratio entre la quantité destinée à la nourriture animale et la quantité destinée à la nourriture (animale + humaine) :**
* 1 - Avoine
* 2 - Manioc
* 3 - Orge

** **

**Question 13 : Combien de tonnes de céréales pourraient être libérées si les USA diminuaient leur production de produits animaux de 10% ?**

In [197]:
# Sélection des lignes de céréales destinées aux animaux aux USA

cereales_alimentation_animale_usa = vegetaux.loc[((vegetaux['Élément'] == 'Aliments pour animaux')
                                                &(vegetaux['Zone'] == 'États-Unis d\'Amérique'))
                                                ]   
prod_animx_USA = cereales_alimentation_animale_usa['Valeur'].sum() * 1000

print('\nProduction d\'aliments pour animaux par les Etats-Unis : {} tonnes\n'.format(prod_animx_USA))


Production d'aliments pour animaux par les Etats-Unis : 145289000.0 tonnes



In [198]:
# Gain potentiel

cereales_liberees_USA = (prod_animx_USA/10)
cereales_liberees_USA
print('\nLes Etats-Unis pourraient libérer {} de tonnes de cérales s\'ils réduisaient leur production d\'aliments pour animaux de 10% '.format(cereales_liberees_USA))



Les Etats-Unis pourraient libérer 14528900.0 de tonnes de cérales s'ils réduisaient leur production d'aliments pour animaux de 10% 


**R13 : Les Etats-Unis pourraient libérer 14528900.0 de tonnes de cérales s'ils réduisaient leur production d'aliments pour animaux de 10%**

** **

**Question 14 : En Thaïlande, quelle proportion de manioc est exportée ? Quelle est la proportion de personnes en sous-nutrition?**

In [199]:
# Production de manioc par la Thaïlande

data_prod_thailande = vegetaux.loc[(vegetaux['Élément']   == 'Production')
                                    &(vegetaux['Zone']    == 'Thaïlande')
                                    &(vegetaux['Produit'] == 'Manioc')
                                    ] 
production_manioc_thailande = data_prod_thailande['Valeur'].sum()
print('\nProduction de manioc par la Thaïlande : {} de milliers de tonnes\n'.format(production_manioc_thailande))


Production de manioc par la Thaïlande : 30228.0 de milliers de tonnes



In [200]:
# Production de manioc exportée par la Thaïlande

data_export_thailande = vegetaux.loc[(vegetaux['Élément'] == 'Exportations - Quantité')
                                    &(vegetaux['Zone']    == 'Thaïlande')
                                    &(vegetaux['Produit'] == 'Manioc')
                                    ] 
exportation_manioc_thailande = data_export_thailande['Valeur'].sum()

print('\nLa Thaïlande exporte {} de milliers de tonnes de manioc\n'.format(exportation_manioc_thailande))


La Thaïlande exporte 25214.0 de milliers de tonnes de manioc



In [201]:
# Proportion de manioc exportée par la Thaïlande
prop = round((25214.0/30228.0),2)*100
print('Proportion de manioc exportée {}%:'.format(prop))

Proportion de manioc exportée 83.0%:


**R14.1 - En Thaïlande, la proportion de manioc est exportée est de 83.0%**

**Question 14.2 : En Thaïlande, quelle est la proportion de personnes en sous-nutrition**

In [202]:
# Population de la Thaïlande en 2013 : 67 011 000 personnes
# Nombre de personnes sous-alimentées en Thaïlande : 5 600 000 personnes
 
# Proportion de personnes sous-alimentées
pourcent_pop_sous_alim = round((5600000/67011000)*100,2)

print('\nProportion de personnes sous-alimentées en Thaïlande : {} %:\n'.format(pourcent_pop_sous_alim))


Proportion de personnes sous-alimentées en Thaïlande : 8.36 %:



**R14.2 - Proportion de personnes sous-alimentées en Thaïlande 8.36 %**



** **

** **

**Partie II - Bases de données relationnelles**

In [203]:
data_merged['dispo_alim_tonnes'] = data_merged['dispo_alim_kg_p']/1000
list(data_merged)

['pays',
 'codePays',
 'annee',
 'produit',
 'codeProduit',
 'origin',
 'alim_ani',
 'autres_utilisations',
 'dispo_alim_kcal_p_j',
 'dispo_alim_kg_p',
 'dispo_mat_gr_g_p_j',
 'dispo_prot_g_p_j',
 'dispo_int',
 'export',
 'import',
 'nourriture',
 'pertes',
 'production',
 'semences',
 'transfo',
 'var_stock',
 'nb_habitants',
 'dispo_alim_tonnes']

In [205]:
# =============================================================================   Préparation des tables à importer dans sqlserver   ===========================================================================================

# population

pop_sql = pop[['codePays', 'pays', 'annee', 'nb_habitants']]
pop_sql.rename(columns = {'codePays':'code_pays','nb_habitants':'population'}, inplace = True)
pop_sql.to_csv(resPath+'pop_sql.csv', index = False)

# dispo_alim

selec_dispo_alim_sql = data_merged[['pays','codePays','annee', 'produit','codeProduit', 'origin', 'dispo_alim_tonnes', 'dispo_alim_kcal_p_j', 'dispo_mat_gr_g_p_j', 'dispo_prot_g_p_j']]
selec_dispo_alim_sql['dispo_prot_g_p_j']    = selec_dispo_alim_sql['dispo_prot_g_p_j'].fillna(0)
selec_dispo_alim_sql['dispo_alim_kcal_p_j'] = selec_dispo_alim_sql['dispo_alim_kcal_p_j'].fillna(0)

     # Sélection des valeurs non nulles de la table 'selec_dispo_alim_sql'

dispo_alim_sql = selec_dispo_alim_sql.loc[
                                          (selec_dispo_alim_sql['dispo_prot_g_p_j'] != 0)
                                         &(selec_dispo_alim_sql['dispo_alim_kcal_p_j'] != 0)
                                         ]
dispo_alim_sql.rename(columns = {'codePays':'code_pays','annee':'année','codeProduit':'code_produit','dispo_prot_g_p_j':'dispo_prot','dispo_mat_gr_g_p_j':'dispo_mat_gr' }, inplace = True)
dispo_alim_sql.to_csv(resPath+'dispo_alim_sql.csv', index = False)

# equilibre_prod

equilibre_prod_sql = data_merged[['pays','codePays','annee', 'produit','codeProduit', 'dispo_int', 'alim_ani', 'semences', 'transfo', 'pertes', 'nourriture', 'autres_utilisations']]
equilibre_prod_sql.rename(columns = {'codePays':'code_pays','annee':'année','codeProduit':'code_produit'}, inplace = True)              
equilibre_prod_sql.to_csv(resPath+'equilibre_prod_sql.csv', index = False)            

# sous_nutrition

sous_nutrition_sql =  sous_nutrition[['Zone','codePays','annee', 'nb_personnes']]   

sous_nutrition_sql.rename(columns={'Zone':'pays','codePays':'code_pays','annee':'année','nb_habitants':'nb_personnes'}, inplace = True)                          
sous_nutrition_sql.to_csv(resPath+'sous_nutrition_sql.csv', index = False)

**FIN**